import {restoredContent,bindSourceGalleries,bindClinicFilm,bindHeroSpecialties,bindMotifMotion,bindSpecialistReviews,originalHero,restoredServiceTail,typesetRussian,originalSource} from './source-content.js';
const A='/st-kids/public/assets/';
const mountHtml=html=>html.replace(/(?<!\/st-kids)\/public\//g,'/st-kids/public/').replace(/(href|src|poster)="\/(?!\/|st-kids\/)/g,'$1="/st-kids/');
const arrow='<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M4 12h15m-6-6 6 6-6 6" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round"/></svg>';
const plus='<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M5 12h14M12 5v14" fill="none" stroke="currentColor" stroke-width="1.5"/></svg>';
const clover='<svg viewBox="0 0 100 100" aria-hidden="true"><path d="M50 26C22-13-13 22 26 50-13 78 22 113 50 74c28 39 63 4 24-24C113 22 78-13 50 26Z" fill="currentColor"/></svg>';
const esc=s=>String(s).replaceAll('₽','Р').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');
const photo=(n,alt='',cls='',eager=false)=>'<img src="'+A+n+'.webp" alt="'+esc(alt)+'" class="'+cls+'" loading="'+(eager?'eager':'lazy')+'" decoding="async"'+(eager?' fetchpriority="high"':'')+'>';
const button=(u,t,c='')=>'<a class="button '+c+'" href="'+u+'"><span>'+t+'</span>'+arrow+'</a>';
const link=(u,t)=>'<a class="text-link" href="'+u+'">'+t+arrow+'</a>';
const nav=[['/about-clinic','О клинике'],['/technique','Методика'],['/services','Услуги и цены'],['/profitable','Выгодно'],['/articles','Статьи'],['/documentation','Пациентам']];
const info={'/':['Клиника ЭСТЕ — ортодонтия и остеопатия в Санкт-Петербурге','Ортодонтическое лечение детей и взрослых с остеопатическим сопровождением. Команда, методика, услуги и цены.'],'/about-clinic':['О клинике — ЭСТЕ','Команда, пространство и подход клиники ЭСТЕ в Санкт-Петербурге.'],'/technique':['Методика — ЭСТЕ','Комплексная диагностика прикуса и осанки, ортодонтическая коррекция и остеопатическое сопровождение.'],'/services':['Услуги и цены — ЭСТЕ','Прайс: ортодонтия, стоматология, остеопатия, протезирование, хирургия, гигиена и пародонтология.'],'/profitable':['Тройной осмотр — ЭСТЕ','Ортодонт, остеопат и стоматолог: комплексный осмотр, рекомендации и письменное заключение.'],'/doctor':['Елена Сесёлкина — ЭСТЕ','Главный врач клиники ЭСТЕ, ортодонт и остеопат. Опыт, образование, лечение детей и взрослых.'],'/articles':['Статьи и истории пациентов — ЭСТЕ','Исследования методики, публикации специалистов и истории пациентов клиники ЭСТЕ.'],'/documentation':['Пациентам — ЭСТЕ','Документы, лицензия, анкеты, договоры и справка для налогового вычета.'],'/privacy':['Политика обработки персональных данных — ЭСТЕ','Политика обработки персональных данных ООО «ЭСТЕ».']};
const path=location.pathname.replace(/^\/st-kids(?=\/|$)/,'').replace(/\/$/,'')||'/';
const docs=[['Реквизиты клиники','1FmEQiFVHYNI-24zDylgu7sC_WGe5OHit'],['Лицензия, патент и разрешение','11imBcIn2GughFjj3b8FqHwcRaleAfNqg'],['Гарантии качества','1WN4kjv_DF0UdRWm-M6K-ChTFfiNVfNuM'],['Договор для взрослых','1pBANUyCfLCi4N3ZTSRZrhc36736irfBh'],['Договор для детей','1u6X6rNQkX3JKX68LVg4dqELeNC_SD1_h'],['Правила оказания и оплаты услуг','1X4K-xo0fozDVe7sicqTMaSEkeAuSHdRe'],['Правила поведения пациентов','1xn7dEDMyzsE4Oz91El4Onmpe_58OhcgY'],['Политика конфиденциальности','1kUIlSwbAN_NnjHtlFkltrKOi76PDmN2J'],['Анкета пациента','1KaeoHOK_jG8IIfpxHbbYx530mIMEsROa'],['Анкета для тройного осмотра','15Fd6Q7AxeVBOnMK0y0vZFJE7u14aOGUq']];
const originalDocumentRecords=originalSource.pages.documentation.filter(r=>r.atoms.some(a=>a.text==='Скачать'));
for(let i=0;i<docs.length;i++)docs[i][0]=originalDocumentRecords[i].atoms.find(a=>a.text.trim()&&a.text!=='Скачать').text;
function originalPriceGroups(){const pairs=[['rec624387692','rec624390945'],['rec625271528','rec624402883'],['rec625271680','rec624407492'],['rec625271804','rec624417583'],['rec625272157','rec624419861'],['rec625272364','rec624421731'],['rec625273013','rec624423453']];return pairs.map(([titleId,rowsId])=>{const records=originalSource.pages.services,title=records.find(r=>r.id===titleId).atoms[0].text,atoms=records.find(r=>r.id===rowsId).atoms;const headings=atoms.filter(a=>parseInt(a.size)>=24&&!a.text.includes('₽')).sort((a,b)=>a.top-b.top);const items=atoms.filter(a=>parseInt(a.size)===20&&!a.text.includes('₽')).map(a=>{const major=headings.filter(h=>parseInt(h.size)>=40&&h.top<=a.top).at(-1),minor=headings.filter(h=>parseInt(h.size)<40&&h.top<=a.top&&h.top>(major?.top??-1)).at(-1);return {name:a.text,price:atoms.find(p=>p.text.includes('₽')&&p.top===a.top)?.text||'',section:[major?.text,minor?.text].filter(Boolean).join(' · '),y:a.top}});return {title,items}})}
const people=[['elena','Елена Сесёлкина','Главный врач, ортодонт-остеопат. Доктор остеопатии, специалист P-DTR, автор патента.','/doctor'],['orthodontist','Василий Лапа','Врач-ортодонт высшей категории.','#contact'],['therapist','Наталья Викулова','Стоматолог-терапевт высшей категории.','#contact'],['curator','Наталья Блашенкова','Куратор лечения — на связи между приёмами.','#contact']];
const crumbs=t=>'<div class="shell breadcrumbs"><a href="/">Главная</a><span>/</span><span>'+t+'</span></div>';
function header(){const homeCue=path==='/'?'':'<small class="brand-home-cue">На главную →</small>';return '<header class="header"><div class="shell header-top"><a class="brand" href="/" aria-label="ЭСТЕ — на главную"><img src="'+A+'logo.svg" width="62" height="62" alt="ЭСТЕ"><span>Клиника ортодонтии<br>и остеопатии'+homeCue+'</span></a><nav id="main-nav" class="navigation" data-nav aria-label="Разделы сайта">'+nav.map(([u,t])=>'<a href="'+u+'" '+(u===path?'aria-current="page"':'')+'>'+t+'</a>').join('')+'<a href="#contact">Контакты</a></nav><a class="header-phone" href="tel:+78125705005">+7 812 570-50-05</a><a class="mobile-phone" href="tel:+78125705005" aria-label="Позвонить в клинику ЭСТЕ"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M7.1 3.8 9.3 7c.4.6.3 1.3-.2 1.8l-1.2 1.1a16.3 16.3 0 0 0 6.2 6.2l1.1-1.2c.5-.5 1.2-.6 1.8-.2l3.2 2.2c.6.4.8 1.1.5 1.8l-1 1.8c-.4.7-1.2 1-2 .8A20 20 0 0 1 2.7 6.3c-.2-.8.1-1.6.8-2l1.8-1c.7-.3 1.4-.1 1.8.5Z" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linejoin="round"/></svg></a><button class="menu-button" data-menu aria-expanded="false" aria-controls="main-nav" aria-label="Открыть меню"><span></span><span></span></button></div></header>'}
function footer(){return '<footer class="footer"><div class="shell footer-top"><div class="footer-identity"><a class="footer-wordmark" href="/" aria-label="ЭСТЕ — на главную">эсте<span>'+clover+'</span></a><p>Клиника ортодонтии<br>и остеопатии</p></div><div class="footer-contact"><span>Запись и вопросы</span><a class="footer-contact-phone" href="tel:+78125705005">+7 812 570-50-05</a><p>Санкт-Петербург, ул. Кременчугская, 21к3</p><a href="https://vk.com/estespb" target="_blank" rel="noreferrer">ВКонтакте '+arrow+'</a></div><nav aria-label="Навигация в подвале">'+nav.map(([u,t])=>'<a href="'+u+'">'+t+'</a>').join('')+'</nav></div><div class="shell footer-bottom"><span>© '+new Date().getFullYear()+' ООО «ЭСТЕ»<br>ИНН 7842170207 · ОГРН 1197847073720</span><a href="/privacy">Политика конфиденциальности</a><a href="/documentation">Документы клиники</a><a href="#top">Наверх ↑</a></div><p class="medical-note shell">Имеются противопоказания. Необходима консультация специалиста.</p></footer>'}
function form(tax=false){return '<form class="form" data-demo-form><h3>'+(tax?'Запросить справку':'Записаться на приём')+'</h3><div class="form-fields"><label>Ваше имя<input name="name" autocomplete="name" placeholder="Как к вам обращаться" required></label><label>'+(tax?'Электронная почта':'Телефон')+'<input name="'+(tax?'email':'phone')+'" type="'+(tax?'email':'tel')+'" autocomplete="'+(tax?'email':'tel')+'" placeholder="'+(tax?'example@mail.ru':'+7 (___) ___-__-__')+'" required></label><label class="field-wide">'+(tax?'Период лечения и комментарий':'С чем хотите обратиться')+'<textarea name="message" rows="2" placeholder="'+(tax?'Укажите год, за который нужна справка':'Кратко опишите вопрос — по желанию')+'"></textarea></label></div><label class="consent"><input type="checkbox" required><span>Я согласен на обработку персональных данных в соответствии с <a href="/privacy">политикой конфиденциальности</a>.</span></label><button class="button" type="submit"><span>'+(tax?'ОТПРАВИТЬ':'Оставить заявку')+'</span>'+arrow+'</button><p class="form-note">Демонстрационная форма: данные пока не отправляются.</p><p class="form-status" role="status"></p></form>'}
function contact(){return '<section class="contact section" id="contact"><div class="shell contact-layout"><div class="contact-copy"><h2>КОНТАКТЫ</h2><a class="contact-phone" href="tel:+78125705005">+7 812 570-50-05</a><address>Санкт-Петербург, ул. Кременчугская, 21к3<br><span>м. Площадь Александра Невского / Площадь Восстания</span></address><div class="contact-links">'+link('https://2gis.ru/spb/firm/5348552838523200','Построить маршрут')+link('https://vk.com/estespb','ВКонтакте')+'</div></div>'+form()+'</div></section>'}
const head=(t,p='',l='')=>'<div class="section-head"><h2>'+t+'</h2><div>'+(p?'<p>'+p+'</p>':'')+l+'</div></div>';
function hero(t,p,im,alt='',extra=''){return crumbs(info[path]?.[0].split(' — ')[0]||'Страница')+'<section class="inner-hero shell"><div><h1>'+t+'</h1><p class="lead">'+p+'</p>'+(extra||button('#contact','Записаться на приём'))+'</div><div class="inner-hero-art">'+photo(im,alt,'',true)+'</div></section>'}
const disclosure=(t,b,open=false)=>'<details class="disclosure" '+(open?'open':'')+'><summary>'+t+'<span>'+plus+'</span></summary><div class="disclosure-body">'+b+'</div></details>';
function team(){return '<section class="section shell" id="team">'+head('Врачи, которые<br><em>работают вместе</em>','Обсуждаем клиническую ситуацию, объясняем рекомендации и сопровождаем пациента на всех этапах лечения.')+'<div class="team-grid">'+people.map(([im,n,r,u])=>'<article class="person"><a class="person-photo" href="'+u+'" aria-label="'+n+': '+(u==='/doctor'?'подробнее о враче':'запись на приём')+'">'+photo(im,n)+'<span>'+arrow+'</span></a><h3>'+n+'</h3><p>'+r+'</p></article>').join('')+'</div></section>'}
function adaptation(){return '<section class="section adaptation" id="adaptation"><div class="shell adaptation-layout"><div class="adaptation-picture">'+photo('about-hero','Знакомство ребёнка с врачом в клинике ЭСТЕ')+'</div><div class="adaptation-copy"><h2>Первый визит —<br><em>через интерес,<br>а не через страх.</em></h2><p class="lead">Знакомимся, играем, объясняем. Помогаем ребёнку почувствовать себя спокойно рядом с врачом.</p><p>Для маленьких пациентов есть отдельный адаптационный приём. Ребёнок знакомится с клиникой и инструментами, а специалист выстраивает контакт в игре.</p><div class="adaptation-facts"><strong>80%</strong><p>наших пациентов —<br>дети и подростки</p></div>'+button('/services#adaptation','Об адаптационном приёме')+'</div></div></section>'}
function offer(){return '<section class="section shell"><div class="offer"><div><h2>Три специалиста.<br><em>Одна понятная<br>картина.</em></h2><p>Ортодонт, остеопат и стоматолог рассматривают вашу ситуацию вместе. После осмотра — ответы на вопросы, рекомендации и письменное заключение.</p><div class="offer-facts"><span><strong>4 500 ₽</strong>стоимость осмотра</span><span><strong>≈ 1,5 часа</strong>продолжительность</span></div>'+button('/profitable','Подробнее о тройном осмотре','button-light')+'</div><div class="offer-art">'+photo('triple-hero','Дети и подростки — пациенты ЭСТЕ')+'</div></div></section>'}
function licenses(){return '<section class="section shell" id="licenses">'+head('ЛИЦЕНЗИИ * СЕРТИФИКАТЫ * ПАТЕНТ ЭСТЕ','',link('/documentation','ДОКУМЕНТЫ КЛИНИКИ'))+'<div class="licenses">'+[['license','Медицинская лицензия'],['license-extra','Приложение к лицензии'],['patent','Патент №2657195'],['sanitary','Санитарное заключение']].map(([im,n])=>'<a href="'+A+im+'.webp" class="license" target="_blank" rel="noreferrer">'+photo(im,n)+'<span>'+n+arrow+'</span></a>').join('')+'</div></section>'}
function reviews(){return '<section class="section shell"><div class="reviews-band"><div><h2>Самое ценное —<br><em>ваше доверие.</em></h2><p>Рассказы пациентов о знакомстве с врачами, лечении и атмосфере клиники.</p></div><div class="reviews-action"><span class="review-flower">'+clover+'</span>'+button('https://yandex.ru/profile/192194227209','Читать отзывы на Яндексе','button-light')+'</div></div></section>'}
function home(){return '<section class="home-hero shell"><div class="hero-copy"><h1>Здоровая улыбка.<br><em>В гармонии<br>с целым телом.</em></h1><p class="lead">Ортодонтия и остеопатия для детей и взрослых в Санкт-Петербурге. Начинаем с диагностики, чтобы увидеть полную картину.</p><div class="hero-actions">'+button('#contact','Записаться на первый приём')+link('/technique','Как мы лечим')+'</div></div><div class="hero-art">'+photo('hero-main','Девочка с моделью зубов — фирменный коллаж клиники ЭСТЕ','',true)+'</div><div class="hero-foot"><span>Прикус и осанка — в единой системе</span><span>Для детей, подростков и взрослых</span><a href="#situations">С чего начать '+arrow+'</a></div></section>'+
'<section class="section situations shell" id="situations">'+head('Что вас<br><em>беспокоит?</em>','До, во время или после ортодонтического лечения — найдём, с какого специалиста начать.')+'<div class="situations-grid">'+[['Прикус','Неровное положение зубов, неправильное смыкание челюстей.','/services#orthodontics','bite'],['Осанка','Сутулость, асимметрия плеч, нарушения положения стоп.','/services#osteopathy','posture'],['Боли','В челюстном суставе, голове, спине или суставах.','/profitable','pain'],['Особый подход','Бережное знакомство с клиникой для детей с особенностями развития.','/doctor','care']].map(([t,d,u,c])=>'<a class="situation '+c+'" href="'+u+'"><h3>'+t+'</h3><p>'+d+'</p><span class="situation-bottom"><span>Подробнее</span>'+arrow+'</span></a>').join('')+'</div></section>'+
'<section class="section approach"><div class="shell approach-layout"><div class="approach-copy"><h2>Смотрим шире,<br><em>чем на ровный<br>зубной ряд.</em></h2><p class="lead">В ЭСТЕ ортодонтия и остеопатия дополняют друг друга. Оцениваем прикус вместе с осанкой и работой мышц.</p><p>Перед выбором аппарата разбираемся в вашей ситуации, объясняем возможные варианты и составляем план лечения.</p>'+button('/technique','Познакомиться с методикой','button-light')+'</div><div class="approach-media">'+photo('spine','Елена Сесёлкина объясняет особенности позвоночника')+'<div class="approach-caption"><strong>Елена Сесёлкина</strong><span>Главный врач, ортодонт-остеопат</span></div></div></div><div class="shell approach-principles"><div><h3>Диагностика до лечения</h3><p>Учитываем состояние зубочелюстной и опорно-двигательной систем.</p></div><div><h3>Сопровождение в процессе</h3><p>Наблюдаем изменения и корректируем план на контрольных приёмах.</p></div><div><h3>Внимание к результату</h3><p>Обсуждаем ретенцию и профилактику после ортодонтической коррекции.</p></div></div></section>'+adaptation()+
'<section class="section shell first-visit">'+head('Клиника начинается<br><em>со знакомства.</em>','Показываем пространство, в котором проходят приёмы. Светлые кабинеты, детская зона и команда рядом.')+'<div class="clinic-gallery"><figure class="gallery-wide">'+photo('team','Команда клиники ЭСТЕ')+'<figcaption>Люди, которым можно задать любой вопрос</figcaption></figure><figure>'+photo('playroom','Детская игровая зона клиники')+'<figcaption>Место для игры перед приёмом</figcaption></figure><figure>'+photo('room-light','Светлый кабинет клиники')+'<figcaption>Пространство для спокойного лечения</figcaption></figure></div>'+link('/about-clinic','Заглянуть в клинику')+'</section>'+offer()+team()+reviews()}
function about(){return hero('Место, где<br><em>вас понимают.</em>','Клиника ЭСТЕ объединяет ортодонтию, стоматологию и остеопатическое сопровождение лечения. Для детей, подростков и взрослых.','about-hero','Врач и ребёнок — фирменный коллаж ЭСТЕ')+
'<section class="section shell"><div class="editorial-split"><h2>Доверие начинается<br><em>с понятного разговора.</em></h2><div><p class="lead">Ни один пациент не должен уйти с приёма без понимания: зачем дана рекомендация, как она поможет в его случае и какие есть варианты.</p><p>Объясняем сложные вещи простым языком. Каждая процедура включает консультацию, а между приёмами на связи остаётся куратор лечения.</p></div></div><figure class="wide-photo">'+photo('team','Команда клиники ЭСТЕ')+'<figcaption>Врачи и команда сопровождения клиники ЭСТЕ</figcaption></figure></section>'+
'<section class="section tinted"><div class="shell">'+head('От диагностики<br><em>до поддержки результата</em>','Не начинаем с выбора брекетов или элайнеров. Сначала изучаем клиническую ситуацию.')+'<div class="service-path"><article><h3>Диагностика</h3><p>Ортодонтическое и остеопатическое обследование, оптическая топография.</p>'+link('/technique','О методике')+'</article><article><h3>Лечение</h3><p>Стоматология, съёмные и несъёмные аппараты, остеопатическое сопровождение.</p>'+link('/services','Услуги и цены')+'</article><article><h3>Профилактика</h3><p>Сохранение результата, полезные привычки, гигиена и адаптация детей.</p>'+link('/services#adaptation','О профилактике')+'</article></div></div></section>'+team()+
'<section class="section shell">'+head('Здесь можно<br><em>почувствовать себя спокойно</em>','Знакомство с клиникой — тоже часть первого визита.')+'<div class="space-gallery">'+[['room-light','Светлые кабинеты'],['room-pink','Оснащение для диагностики и лечения'],['playroom','Детская зона ожидания']].map(([im,t])=>'<figure>'+photo(im,t)+'<figcaption>'+t+'</figcaption></figure>').join('')+'</div><div id="clinic-video" class="video-block"><div><h3>Небольшая экскурсия по ЭСТЕ</h3><p>Посмотрите, как устроена клиника и как проходит знакомство со специалистами.</p></div><video controls preload="none" poster="'+A+'room-light.webp" aria-label="Видео о клинике ЭСТЕ"><source src="/public/assets/clinic-tour.mp4" type="video/mp4"></video></div></section>'+adaptation()+licenses()+reviews()}
function technique(){return hero('Лечим прикус.<br><em>Учитываем<br>целый организм.</em>','Методика объединяет ортодонтическую диагностику, остеопатическое обследование и сопровождение во время коррекции прикуса.','technique-hero','Фирменный коллаж с детьми клиники ЭСТЕ',button('/profitable','Начать с комплексного осмотра'))+
'<section class="section shell"><div class="editorial-split"><h2>Почему важно<br><em>посмотреть шире?</em></h2><div><p class="lead">Брекеты и элайнеры изменяют положение зубов. Поэтому план лечения начинается с обследования, а не только с желаемой формы улыбки.</p><p>В ЭСТЕ оценивают прикус, работу челюстного сустава, мышц и состояние осанки. Это помогает специалистам согласовать дальнейшие действия.</p></div></div><div class="method-pair"><figure>'+photo('scan','Врач анализирует диагностический снимок')+'<figcaption>Ортодонтическая диагностика</figcaption></figure><figure>'+photo('visit','Остеопатическое обследование ребёнка')+'<figcaption>Остеопатическое обследование</figcaption></figure></div></section>'+
'<section class="section approach"><div class="shell">'+head('Одна методика.<br><em>Несколько взаимосвязанных этапов.</em>','Состав обследования и лечения зависит от вашей клинической ситуации.')+'<div class="method-steps">'+[['01','Ортодонтическая диагностика','Осмотр зубов, зубных дуг и прикуса, оценка мышц и челюстного сустава, анализ диагностических снимков.'],['02','Остеопатическое обследование','Оценка состояния опорно-двигательного аппарата, осанки и функциональных особенностей.'],['03','Оптическая топография','Исследование рельефа поверхности спины. Помогает оценить положение тела без рентгеновской нагрузки.'],['04','Ортодонтическая коррекция','Лечение с применением съёмных или несъёмных аппаратов, подобранных по результатам диагностики.'],['05','Остеопатическое сопровождение','Наблюдение и коррекция по показаниям до, во время и после ортодонтического лечения.']].map(([n,t,d])=>'<article><span>'+n+'</span><h3>'+t+'</h3><p>'+d+'</p></article>').join('')+'</div></div></section>'+
'<section class="section shell"><div class="editorial-split"><h2>Что входит<br><em>в первичную диагностику</em></h2><div>'+disclosure('История и стоматологический осмотр','<p>Обсуждение жалоб и анамнеза, осмотр зубов и полости рта, анализ зубных дуг и прикуса.</p>',true)+disclosure('Мышцы и челюстной сустав','<p>Пальпация мышц и височно-нижнечелюстного сустава, визуальный анализ движения нижней челюсти.</p>')+disclosure('Инструментальное обследование','<p>Аппаратная диагностика, расчёт снимков и оптическая топография по показаниям.</p>')+disclosure('Функциональная оценка','<p>Остеопатические тесты и оценка состояния опорно-двигательного аппарата.</p>')+'</div></div></section>'+
'<section class="section tinted"><div class="shell patent-layout"><a href="'+A+'patent.webp" target="_blank" rel="noreferrer">'+photo('patent','Патент №2657195')+'</a><div><h2>От клинической практики<br><em>к собственной методике</em></h2><p class="lead">Елена Сесёлкина — автор патента №2657195 на способ диагностики опорно-двигательного аппарата при планировании стоматологического лечения.</p><p>Методика выросла из совместной работы в ортодонтии и остеопатии. План и ожидаемые результаты врач обсуждает с каждым пациентом индивидуально.</p>'+button('/doctor','Познакомиться с автором методики')+'</div></div></section>'+restoredServiceTail()}
async function services(){const groups=originalPriceGroups(),ids=['orthodontics','dentistry','osteopathy','prosthetics','surgery','adaptation','periodontology'];return originalHero('services')+
'<section class="section shell" id="price-list"><div class="price-intro"><div><h2>Услуги и цены</h2></div><label class="search-field">Поиск по прайсу<input type="search" data-price-search placeholder="Например, элайнеры или гигиена"></label></div><div class="price-layout"><nav class="price-nav" aria-label="Направления лечения">'+groups.map((g,i)=>'<a href="#'+ids[i]+'">'+g.title+arrow+'</a>').join('')+'</nav><div class="price-groups">'+groups.map((g,i)=>'<details class="price-category" id="'+ids[i]+'"><summary><h3>'+g.title+'</h3><span aria-hidden="true">＋</span></summary><div class="price-category-content"><p class="price-audience">Дети<br>Подростки<br>Взрослые</p>'+Object.entries(g.items.reduce((a,r)=>{(a[r.section]??=[]).push(r);return a},{})).map(([t,items])=>'<details class="price-disclosure"><summary>'+t.charAt(0)+t.slice(1).toLowerCase()+plus+'</summary><div>'+items.map(r=>'<div class="price-row" data-price-row><span>'+esc(r.name)+'</span><strong>'+esc(r.price)+'</strong></div>').join('')+'</div></details>').join('')+'</div></details>').join('')+'<p class="search-empty" hidden>По вашему запросу ничего не найдено. Попробуйте другое слово или позвоните нам.</p></div></div></section>'+restoredServiceTail()}
function profitable(){return hero('Тройной осмотр.<br><em>Вместе видим больше.</em>','Три специалиста, один визит и согласованные рекомендации. Для тех, кто хочет разобраться в своей ситуации и понять дальнейшие шаги.','triple-hero','Дети и подростки в фирменном коллаже ЭСТЕ','<div class="hero-price"><strong>4 500 ₽</strong><span>около 1,5 часа</span></div>'+button('#contact','Записаться на тройной осмотр'))+
'<section class="section shell"><div class="consultation-system"><div class="consultation-heading"><h2>Три взгляда<br><em>на вашу ситуацию</em></h2><p>Вместо отдельных визитов и разрозненных заключений — осмотр в одной клинике.</p></div><div class="consultation-roles">'+[['01','Ортодонт','Прикус, положение зубов и работа челюстного сустава.'],['02','Остеопат','Осанка и функциональное состояние опорно-двигательной системы.'],['03','Стоматолог','Состояние зубов, полости рта и задачи стоматологического лечения.']].map(([n,t,p])=>'<article><span>'+n+'</span><h3>'+t+'</h3><p>'+p+'</p></article>').join('')+'</div><div class="consultation-result"><span>'+clover+'</span><div><h3>Общее заключение</h3><p>Ответы на ваши вопросы, рекомендации и письменный план дальнейших действий.</p></div></div></div></section>'+
'<section class="section tinted"><div class="shell">'+head('Когда стоит<br><em>начать с осмотра</em>','Не нужно самостоятельно выбирать диагноз. Расскажите о том, что замечаете, — специалисты определят необходимый объём обследования.')+'<div class="audience-list">'+[['Детям','Если беспокоят положение зубов, прикус, осанка или стопы; есть вопросы к дыханию, речи и привычкам ребёнка.'],['Подросткам','При сочетании нарушений прикуса и осанки, перед началом ортодонтического лечения.'],['Взрослым','Перед коррекцией улыбки, при дискомфорте в челюстном суставе или необходимости согласовать рекомендации специалистов.']].map(([t,p])=>'<article><h3>'+t+'</h3><p>'+p+'</p></article>').join('')+'</div></div></section>'+
'<section class="section shell"><div class="visit-layout"><figure>'+photo('visit','Осмотр ребёнка специалистом клиники ЭСТЕ')+'</figure><div><h2>Что будет<br><em>на приёме</em></h2><ol class="visit-steps"><li><h3>Знакомство и ваши вопросы</h3><p>Обсуждаем жалобы, историю лечения и ожидания.</p></li><li><h3>Осмотр специалистами</h3><p>Оцениваем зубочелюстную систему и функциональные особенности.</p></li><li><h3>Обсуждение результатов</h3><p>Объясняем рекомендации, возможные варианты и выдаём письменное заключение.</p></li></ol>'+button('#contact','Выбрать время приёма')+'</div></div></section>'+team()+adaptation()}
function doctor(){return hero('Елена Леонидовна<br><em>Сесёлкина</em>','Главный врач, ортодонт-остеопат, доктор остеопатии, специалист P-DTR. Автор патента на диагностический метод.','doctor-hero','Елена Сесёлкина с маленькой пациенткой')+
'<section class="section shell"><div class="doctor-story"><div class="doctor-story-photo">'+photo('spine','Елена Сесёлкина с моделью позвоночника')+'</div><div><h2>Ортодонтия и остеопатия —<br><em>в одной практике</em></h2><p class="lead">Более 20 лет в стоматологии. В центре внимания — не только эстетика улыбки, но и функциональные особенности пациента.</p><p>Елена Леонидовна ведёт ортодонтический и остеопатический приём детей и взрослых с нарушениями прикуса, осанки и дисфункцией ВНЧС.</p><p>С 2019 года принимает детей с особенностями развития, в том числе с ДЦП, аутизмом, задержкой речи и развития.</p>'+link('/technique','Подробнее о методике')+'</div></div></section>'+
'<section class="section tinted"><div class="shell editorial-split"><h2>Образование<br><em>и профессиональный путь</em></h2><div class="timeline">'+[['1999','Ординатура в МГСУ.'],['2013','Русская Высшая Школа Остеопатии.'],['2014','Международный диплом в Монреале. Тема — остеопатическое сопровождение ортодонтического лечения детей в сменном прикусе.'],['2015','Доклад на VI Всемирном конгрессе лингвальных ортодонтов в Сеуле.'],['Патент','Автор способа диагностики опорно-двигательного аппарата при планировании и проведении стоматологического лечения, №2657195.']].map(([y,t])=>'<div><strong>'+y+'</strong><p>'+t+'</p></div>').join('')+'</div></div></section>'+
'<section class="section shell"><div class="doctor-story reverse"><div class="doctor-story-photo">'+photo('teenagers','Елена Сесёлкина с пациентами-подростками')+'</div><div><h2>Вы понимаете,<br><em>что происходит<br>и зачем.</em></h2><p class="lead">Доверие строится на понятной логике лечения.</p><p>Врач объясняет, почему рекомендует процедуру, как она связана с вашей ситуацией и какие альтернативы можно рассмотреть.</p>'+button('#contact','Записаться к главному врачу')+'<p class="small-note">Стоимость и формат первичного приёма уточнит администратор.</p></div></div></section>'+reviews()}
function articles(){return hero('Практика, исследования<br><em>и истории людей.</em>','Рассказываем о комплексном подходе к лечению, профилактике и сохранению результатов ортодонтической коррекции.','technique-hero','Дети — пациенты клиники ЭСТЕ',link('/technique','Изучить методику'))+
'<section class="section shell publications"><article><h2>Статьи<br><em>и публикации</em></h2><p>Клиника изучает влияние зубочелюстных аномалий и ортодонтических аппаратов на состояние скелетно-мышечной системы. Результаты исследований применяются в работе специалистов.</p><div class="publication-status"><h3>Публикации временно недоступны</h3><p>Можно познакомиться с описанием методики и её диагностических этапов.</p>'+link('/technique','Открыть описание методики')+'</div></article><article><h2>Истории<br><em>наших пациентов</em></h2><p>Дневник лечения публикуется только с разрешения пациентов. В нём важны не только результаты, но и сложности, с которыми сталкивались люди на своём пути.</p><div class="publication-status"><h3>Истории временно недоступны</h3><p>Отзывы о приёмах и специалистах можно прочитать на странице клиники в Яндексе.</p>'+link('https://yandex.ru/profile/192194227209','Читать отзывы пациентов')+'</div></article></section>'}
function documentation(){const groups=[['Лицензии и реквизиты',docs.slice(0,3)],['Договоры и правила',docs.slice(3,8)],['Анкеты',docs.slice(8)]];return crumbs('Пациентам')+'<section class="text-hero shell"><h1>Документы клиники</h1><nav class="document-jumps" aria-label="Группы документов"><a href="#licenses-docs">Лицензии и реквизиты</a><a href="#rules-docs">Договоры и правила</a><a href="#forms-docs">Анкеты</a></nav></section><section class="section shell documents-layout"><div><h2>ДОКУМЕНТЫ КЛИНИКИ</h2></div><div class="document-groups">'+groups.map(([title,items],i)=>'<section id="'+['licenses-docs','rules-docs','forms-docs'][i]+'" class="document-group"><h3>'+title+'</h3><div class="document-list">'+items.map(([name,id])=>{const downloadable=/Анкета/i.test(name)||/Договор/i.test(name);const url=downloadable?'https://drive.google.com/uc?export=download&id='+id:'https://drive.google.com/file/d/'+id+'/view';return '<a href="'+url+'" target="_blank" rel="noreferrer"><span>'+name+'</span><span class="document-action">'+(/Анкета/i.test(name)?'Скачать анкету':/Договор/i.test(name)?'Скачать договор':/Лицензия/i.test(name)?'Открыть лицензию':'Открыть документ')+'</span>'+arrow+'</a>'}).join('')+'</div></section>').join('')+'</div></section>'+licenses()+'<section class="section tinted" id="tax"><div class="shell contact-layout"><div><h2>ЗАПРОС СПРАВКИ ДЛЯ НАЛОГОВОГО ВЫЧЕТА</h2><p class="lead">СПРАВКА ДЛЯ НАЛОГОВОЙ БУДЕТ НАПРАВЛЕНА ВАМ НА УКАЗАННЫЙ ЭЛЕКТРОННЫЙ АДРЕС</p></div>'+form(true)+'</div></section>'}
async function privacy(){const p=await fetch('/st-kids/public/data/privacy.json').then(r=>r.json());return crumbs('Политика конфиденциальности')+'<section class="text-hero shell"><h1>Политика обработки<br><em>персональных данных</em></h1><p>ООО «ЭСТЕ»</p></section><article class="shell legal">'+p.map(t=>/^\d+\.\s/.test(t)&&t.length<100?'<h2>'+esc(t)+'</h2>':'<p>'+esc(t)+'</p>').join('')+'</article>'}
const renderers={'/':home,'/about-clinic':about,'/technique':technique,'/services':services,'/profitable':profitable,'/doctor':doctor,'/articles':articles,'/documentation':documentation,'/privacy':privacy};
const content=restoredContent(path)??(renderers[path]?await renderers[path]():'<section class="text-hero shell"><h1>Страница не найдена</h1>'+button('/','На главную')+'</section>');
document.title=(info[path]||['Страница не найдена — ЭСТЕ'])[0];document.querySelector('meta[name="description"]').content=(info[path]||['','Клиника ЭСТЕ'])[1];
document.querySelector('#app').innerHTML=mountHtml('<div id="top">'+header()+'<main id="main" class="route-'+(path==='/'?'home':path.slice(1))+'">'+content+'</main>'+(path==='/privacy'?'':contact())+footer()+'</div>');
const textNodes=document.createTreeWalker(document.querySelector('#app'),NodeFilter.SHOW_TEXT);
while(textNodes.nextNode()){
 const node=textNodes.currentNode;
 if(node.parentElement?.closest('script,style,noscript,textarea,code,pre'))continue;
 node.textContent=typesetRussian(node.textContent);
}
if(path==='/privacy')document.querySelectorAll('a[href="#contact"]').forEach(a=>a.setAttribute('href','/st-kids/#contact'));
document.querySelectorAll('.brand img').forEach(im=>im.src='/st-kids/public/assets/source/ae44d31cd52d.svg');
bindSourceGalleries();
bindClinicFilm();
bindMotifMotion();
bindSpecialistReviews();
bindHeroSpecialties();
const menu=document.querySelector('[data-menu]'),navEl=document.querySelector('[data-nav]');
function setMenu(open){menu.setAttribute('aria-expanded',String(open));menu.setAttribute('aria-label',open?'Закрыть меню':'Открыть меню');navEl.classList.toggle('open',open);}
menu.addEventListener('click',()=>setMenu(menu.getAttribute('aria-expanded')!=='true'));
navEl.addEventListener('click',e=>{if(e.target.closest('a'))setMenu(false)});
document.addEventListener('keydown',e=>{if(e.key==='Escape'&&menu.getAttribute('aria-expanded')==='true'){setMenu(false);menu.focus()}});
matchMedia('(min-width: 1101px)').addEventListener('change',e=>{if(e.matches)setMenu(false)});
document.querySelectorAll('[data-demo-form]').forEach(f=>f.addEventListener('submit',e=>{e.preventDefault();if(f.reportValidity())f.querySelector('.form-status').textContent='Форма заполнена корректно. Это локальная версия: заявка не отправлена. Для записи позвоните +7 812 570-50-05.'}));
document.querySelector('[data-price-search]')?.addEventListener('input',e=>{const q=e.target.value.toLowerCase().trim();let count=0;document.querySelectorAll('.price-category').forEach(c=>{let total=0;c.querySelectorAll('.price-disclosure').forEach(d=>{let found=0;d.querySelectorAll('[data-price-row]').forEach(r=>{const show=!q||(r.textContent+' '+d.querySelector('summary').textContent+' '+c.querySelector('h3').textContent).toLowerCase().includes(q);r.hidden=!show;if(show)found++});d.hidden=!!q&&!found;d.open=!!q&&!!found;total+=found});c.hidden=!!q&&!total;c.open=!!q&&!!total;count+=total});document.querySelector('.search-empty').hidden=count>0;});
document.querySelectorAll('.price-nav a').forEach(a=>a.addEventListener('click',()=>{const category=document.querySelector(a.getAttribute('href'));if(category?.matches('.price-category'))category.open=true}));
if(location.hash)requestAnimationFrame(()=>{const target=document.getElementById(decodeURIComponent(location.hash.slice(1)));if(target?.matches('.price-category'))target.open=true;target?.scrollIntoView()});
