// Original clinic content is kept separately from layout. Do not paraphrase it.
const source=await fetch('/st-kids/public/data/source-pages.json').then(r=>r.json());
const E=s=>String(s).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');
const arrow='<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M4 12h15m-6-6 6 6-6 6" fill="none" stroke="currentColor" stroke-width="1.7"/></svg>';
const unique=a=>a.filter((x,i)=>a.findIndex(y=>y.text===x.text)===i);
const rec=(page,id)=>source.pages[page].find(r=>r.id===id);
const img=(im,alt='',cls='',loading='lazy')=>'<img class="'+cls+'" src="'+source.assets[im.url]+'" alt="'+E(alt)+'" loading="'+loading+'" decoding="async">';
const target=h=>h?.startsWith('#popup:')?'#contact':h?.startsWith('#open')?'#detail-'+h.slice(1):h;
const button=(h,t,c='')=>'<a class="button '+c+'" href="'+E(target(h)||'#contact')+'"><span>'+E(t)+'</span>'+arrow+'</a>';
// Emphasize only verified phrases from the original copy; the wording stays intact.
const emphasisByRecord={
 rec622022822:['агрессивным ортодонтическим лечением','организм человека не всегда безобидно на них реагирует'],
 rec626995065:['80% наших пациентов - дети и подростки','положительный опыт общения','АДАПТАЦИОННЫЙ ПРИЕМ-знакомство','снимать стресс в игре'],
 rec622025102:['осмотр и консультацию сразу трех специалистов по цене одного'],
 rec622031542:['закрепить его без агрессивного вреда и стресса'],
 rec622040175:['сотрудничество между врачом и клиентом рождается в ДОВЕРИИ'],
 rec622049173:['диагностики зубочелюстной системы в комплексе','без вреда пациенту'],
 rec622050389:['врачебное мнение','на основании нашей статистики и результатов диагностики'],
 rec627003393:['80% наших пациентов - дети и подростки','адаптационный прием-знакомство','снимать стресс в игре'],
 rec624044039:['дискомфорт и боль','нарушаем функции организма'],
 rec624065448:['мягко и эффективно работать над эстетикой улыбки','ОСТЕОПАТИЧЕСКОЕ СОПРОВОЖДЕНИЕ АДАПТИРУЕТ ТКАНИ К ИЗМЕНЕНИЯМ'],
 rec624843982:['системные рекомендации','без комплексной диагностики на входе'],
 rec622068228:['закрепить его без агрессивного вреда и стресса'],
 rec626524092:['исключительно с разрешения наших клиентов','истории неуспеха']
};
const paras=(t,id)=>(id==='rec624843982'&&t.startsWith('Все в нашем организме')?t.replace('. Если ','.\nЕсли '):t).trim().split(/\n+/).filter(Boolean).map(p=>{
 let html=E(p);
 for(const phrase of emphasisByRecord[id]||[])html=html.replaceAll(E(phrase),'<strong>'+E(phrase)+'</strong>');
 return '<p>'+html+'</p>';
}).join('');
function photos(r){return r.images.filter((im,i,a)=>!/\.svg/.test(im.url)&&a.findIndex(x=>x.url===im.url)===i)}
function gallery(r){const media=photos(r),slides=media.filter(im=>im.class.includes('slds'));const displacedPortraits=['rec622031542','rec624840701','rec624826019','rec622068228'].includes(r.id)?media.filter(im=>!im.class.includes('slds')):[];const all=slides.length>1?[...slides.slice(1),slides[0],...displacedPortraits]:media;if(!all.length)return '';const topic=r.atoms.find(a=>parseInt(a.size)>=40)?.text.trim()||'клиники ЭСТЕ';const auto=all.length>1;return '<div class="source-gallery" data-gallery><div class="source-gallery-track" tabindex="0" aria-label="Фотографии: '+E(topic)+'. Прокручивайте вбок">'+all.map((im,i)=>'<figure>'+img(im,im.alt||'Фото '+(i+1)+' из '+all.length+': '+topic,'',i===0&&source.pages.home.includes(r)?'eager':'lazy')+'</figure>').join('')+'</div>'+(all.length>1?'<div class="gallery-controls"><span class="gallery-count"><b data-gallery-index>01</b> / '+String(all.length).padStart(2,'0')+'</span>'+(auto?'<button type="button" class="gallery-pause" data-autoplay-toggle aria-pressed="false" aria-label="Остановить автопрокрутку"><span aria-hidden="true">Ⅱ</span></button>':'')+'<button type="button" data-slide="-1" aria-label="Предыдущее фото">'+arrow+'</button><button type="button" data-slide="1" aria-label="Следующее фото">'+arrow+'</button></div>':'')+'</div>'}
function copy(r){const a=unique(r.atoms.filter(x=>x.text.trim()&&!/^[<>]$/.test(x.text.trim())));const ctas=a.filter(x=>x.href&&parseInt(x.size)===24||x.href&&/^(ВСЕ УСЛУГИ|ЗАПИСАТЬСЯ)/.test(x.text)||r.id==='rec625263103'&&x.text.trim()==='ЗАПИСАТЬСЯ');const experience=r.atoms.find(x=>x.text.startsWith('Уже 17 лет'));const body=a.filter(x=>!ctas.includes(x)&&x!==experience);const main=body.find(x=>parseInt(x.size)>=40);let html=main?'<h2>'+E(main.text.trim())+'</h2>':'';
 const rest=body.filter(x=>x!==main);const ordered=[...rest].sort((a,b)=>a.top-b.top||a.left-b.left);let groups=[];
 const headings=ordered.filter(a=>parseInt(a.size)>=24);groups=headings.map(a=>({heading:a.text,anchor:a,items:[]}));
 for(const item of ordered.filter(a=>!headings.includes(a))){const candidates=groups.filter(g=>g.anchor&&g.anchor.top<=item.top+3).sort((a,b)=>(Math.abs(a.anchor.left-item.left)*3+Math.abs(a.anchor.top-item.top))-(Math.abs(b.anchor.left-item.left)*3+Math.abs(b.anchor.top-item.top)));if(candidates.length)candidates[0].items.push(item);else{let intro=groups.find(g=>!g.anchor);if(!intro){intro={heading:'',items:[]};groups.unshift(intro)}intro.items.push(item)}}
 html+='<div class="source-copy-groups '+(groups.length>1?'multiple':'')+'">'+groups.map(g=>'<div>'+(g.heading?'<h3>'+E(g.heading.trim()==='ОСОБЫЕ ДЕТИ'?'ДЕТИ, КОТОРЫМ НУЖЕН ОСОБЫЙ ПОДХОД':g.heading.trim())+'</h3>':'')+g.items.map(a=>paras(a.text,r.id)).join('')+'</div>').join('')+'</div>';
 if(experience)html+='<aside class="experience-callout"><p>'+E(experience.text).replace('17 лет','<strong>17 лет</strong>')+'</p></aside>';
 html+='<div class="source-actions">'+ctas.map(a=>button(a.href,a.text)).join('')+'</div>';return html;
}
function profitableComparison(r){const item=t=>r.atoms.find(a=>a.text.trim()===t)?.text||t;const summary=['ЭКОНОМИЯ ВРЕМЕНИ','ЗАПАТЕНТОВАННАЯ МЕТОДИКА'].map(t=>{const a=r.atoms.find(x=>x.text===t),body=r.atoms.find(x=>parseInt(x.size)===20&&x.left===a.left&&x.top>a.top);return '<article class="comparison-note"><h3>'+E(t)+'</h3>'+paras(body.text,r.id)+'</article>'}).join('');return '<div class="comparison-layout"><div class="market-price"><h3>'+E(item('СРЕДНЯЯ СТОМОСТЬ ПРИЕМА В СПБ'))+'</h3><p>'+E(item('Ортодонт+Остеопат+Стоматолог Спб'))+'</p><strong>12 000 руб.</strong></div><div class="clinic-offer"><div class="clinic-price"><h3>'+E(item('“Тройной осмотр” в ЭСТЕ'))+'</h3><strong>4 500 руб.</strong><span>'+E(item('-65%'))+'</span></div><div class="comparison-notes">'+summary+'</div></div></div><div class="source-actions">'+button('#contact','ЗАПИСАТЬСЯ')+'</div>'}
function teamCards(r){const staff=[['ЕЛЕНА СЕСЁЛКИНА','Главный врач, ортодонт-остеопат, доктор остеопатии, специалист P-DTR, автор патента'],['НАТАЛЬЯ БЛАШЕНКОВА','Куратор лечения'],['НАТАЛЬЯ ВИКУЛОВА','Стоматолог-терапевт высшей категории'],['ВАСИЛИЙ ЛАПА','Врач-ортодонт высшей категории']];const portraits=photos(r);return '<section class="source-team section shell" id="'+r.id+'" data-source-record="'+r.id+'" aria-label="Специалисты клиники ЭСТЕ"><div class="team-cards">'+staff.map(([name,role],i)=>'<figure class="team-card">'+img(portraits[i],name,'','lazy')+'<figcaption><h3>'+E(name)+'</h3><p>'+E(role)+'</p></figcaption></figure>').join('')+'</div><div class="source-actions">'+button('#contact','ЗАПИСАТЬСЯ')+'</div></section>'}
function protocolCards(r){const title=r.atoms.find(a=>parseInt(a.size)>=40).text;const statements=r.atoms.find(a=>a.text.includes('Не беремся')).text.split(/\n\s*\n+/).map(x=>x.trim()).filter(Boolean);return '<section class="source-protocols section shell" id="'+r.id+'" data-source-record="'+r.id+'"><h2>'+E(title)+'</h2><div class="protocol-grid">'+statements.map(s=>'<article><p>'+E(s)+'</p></article>').join('')+'</div>'+gallery(r)+'</section>'}
function trustBlock(r){const heading=r.atoms.find(a=>parseInt(a.size)>=40).text;const prose=r.atoms.filter(a=>parseInt(a.size)===20);const [principle,...questions]=prose[1].text.split(/\n+/).map(s=>s.trim()).filter(Boolean);return '<section class="source-trust section shell" id="'+r.id+'" data-source-record="'+r.id+'"><div class="trust-content"><div class="trust-intro"><h2>'+E(heading)+'</h2>'+paras(prose[0].text,r.id)+'<p>'+E(principle)+'</p></div><ul class="trust-questions">'+questions.map(q=>'<li>'+E(q)+'</li>').join('')+'</ul></div>'+gallery(r)+'</section>'}
function examinationBlock(r){const pairs=[[8,9],[0,1],[2,3],[4,5],[6,7]];return '<section class="source-examination section shell" id="'+r.id+'" data-source-record="'+r.id+'"><div class="examination-list">'+pairs.map(([h,p],i)=>'<article class="examination-step"><span class="examination-number">0'+(i+1)+'</span><div><h2>'+E(r.atoms[h].text)+'</h2>'+paras(r.atoms[p].text,r.id)+'</div></article>').join('')+'<div class="source-actions">'+button(r.atoms[10].href||'/services',r.atoms[10].text)+'</div></div>'+gallery(r)+'</section>'}
function orthodontistBlock(r){const heading=r.atoms[0].text;const sentences=r.atoms[1].text.split(/(?<=\.)\s+(?=[А-Я])/).filter(Boolean);return '<section class="source-orthodontist section shell" id="'+r.id+'" data-source-record="'+r.id+'"><div class="orthodontist-copy"><h2>'+E(heading)+'</h2><div class="orthodontist-points">'+sentences.map(s=>'<p>'+E(s)+'</p>').join('')+'</div></div>'+gallery(r)+'</section>'}
function serviceCallout(r){const a=r.atoms;return '<section class="source-service-callout section shell" id="'+r.id+'" data-source-record="'+r.id+'"><div><h2>'+E(a.find(x=>parseInt(x.size)>=40&&x.text!=='5000₽').text)+'</h2><p>'+E(a.find(x=>x.text.startsWith('СТОИМОСТЬ')).text)+'</p><strong>5 000 руб.</strong></div><div class="source-actions">'+button('#contact','Записаться на диагностику')+'</div>'+gallery(r)+'</section>'}
function block(r){if(['rec622041249','rec634682611'].includes(r.id))return teamCards(r);if(r.id==='rec622049173')return protocolCards(r);if(['rec622040175','rec625272280'].includes(r.id))return trustBlock(r);if(r.id==='rec624075708')return examinationBlock(r);if(r.id==='rec624062019')return orthodontistBlock(r);if(r.id==='rec625263103')return serviceCallout(r);const media=photos(r),hasSlides=media.some(im=>im.class.includes('slds')),portraits=hasSlides&&!['rec622031542','rec624840701','rec624826019','rec622068228'].includes(r.id)?media.filter(im=>!im.class.includes('slds')):[];const hasCopy=r.atoms.some(a=>a.text.trim()&&!/^[<>]$/.test(a.text.trim()));if(!hasCopy&&media.length)return '<section class="source-section section shell media-only" id="'+r.id+'" data-source-record="'+r.id+'">'+gallery(r)+'</section>';const benefits=r.id==='rec622009100'?'<h2>'+E(r.atoms.find(a=>parseInt(a.size)>=40).text)+'</h2><div class="method-benefits">'+r.atoms.filter(a=>parseInt(a.size)===20&&!a.href).map((a,i)=>'<article><span>0'+(i+1)+'</span><h3>'+E(a.text)+'</h3></article>').join('')+'</div><div class="source-actions">'+button('/technique','Больше о методике')+'</div>':r.id==='rec624845903'?profitableComparison(r):copy(r);return '<section class="source-section section shell '+(media.length?'has-media':'')+'" id="'+r.id+'" data-source-record="'+r.id+'"><div class="source-copy">'+benefits+(portraits.length?'<div class="source-portraits">'+portraits.map(im=>img(im,'Специалисты клиники ЭСТЕ')).join('')+'</div>':'')+'</div>'+gallery(r)+'</section>'}
function directory(){const r=rec('home','rec622016700'),p=photos(r);const entries=[['О КЛИНИКЕ','Главный врач · Команда · Аппараты · Запись на приём','/about-clinic'],['МЕТОДИКА','Медицинский патент · Эффективность','/technique'],['УСЛУГИ','Диагностика · Лечение · Реабилитация','/services'],['ВЫГОДНО','Тройной осмотр · Лучшая цена СПб','/profitable'],['ПУБЛИКАЦИИ','Статьи · Истории клиентов','/articles']];const descriptions=['Команда клиники ЭСТЕ','Портрет маленького ребёнка','Подросток показывает ортодонтическую капу','Девочка с моделью зубов','Улыбающийся ребёнок'];return '<section class="section shell source-directory" aria-labelledby="directory-title" data-source-record="'+r.id+'"><h2 class="directory-heading" id="directory-title">Разделы клиники</h2>'+entries.map(([t,d,u],i)=>'<a class="directory-entry" href="'+u+'"><div><h2>'+t+'</h2><p>'+d+'</p><span class="directory-arrow">'+arrow+'</span></div><div class="brand-photo '+(i%2?'bird-photo':'clover-photo')+'">'+img(p[i],descriptions[i],'','eager')+'</div></a>').join('')+'<a class="directory-last" href="/doctor"><span>Приём детей</span>'+arrow+'</a></section>'}
function clinicVideo(){return '<section class="clinic-film section shell" aria-labelledby="clinic-film-title"><video class="source-video" muted loop playsinline preload="none" poster="/public/assets/room-light.webp"><source src="/public/assets/clinic-tour.mp4" type="video/mp4">Ваш браузер не поддерживает воспроизведение видео.</video><div class="clinic-film-copy"><p>ЭСТЕ изнутри</p><h2 id="clinic-film-title">Видео о клинике</h2><button class="film-toggle" type="button" aria-label="Воспроизвести видео">Смотреть видео</button></div></section>'}
function home(){return '<section class="home-hero shell original-hero"><div class="hero-content"><p class="hero-eyebrow">Клиника ЭСТЕ · Санкт-Петербург</p><h1>ЭСТЕ</h1><div class="original-specialties" aria-label="Стоматология, ортодонтия, остеопатия"><span class="specialty-text" data-specialty-text>Стоматология</span><span class="specialty-caret" aria-hidden="true"></span><button type="button" class="specialty-toggle" aria-label="Остановить смену направлений" aria-pressed="false">Ⅱ</button></div><div class="hero-actions">'+button('#contact','Записаться на приём')+button('/technique','Больше о методике','button-outline')+'</div></div><div class="hero-art"><img src="/public/assets/hero-main.webp" alt="ЭСТЕ — стоматология, ортодонтия, остеопатия" fetchpriority="high"></div></section>'+block(rec('home','rec622009100'))+block(rec('home','rec622015033'))+directory()+block(rec('home','rec622022822'))+clinicVideo()+block(rec('home','rec626995065'))+block(rec('home','rec622025102'))}
const sections={
 'about-clinic':['rec622031542','rec625193524','rec630123451','rec622036080','rec622040175','rec622041249','rec622049173','rec622050389','rec622054959','rec622055204','rec622055876','rec622060036','rec622061458','rec622061536','rec627003393','rec625232442'],
 'technique':['rec624044039','rec624062019','rec624063674','rec624065448','rec624073439','rec624074967','rec624075708','rec627012913','rec625253182'],
 'profitable':['rec624840701','rec624841252','rec624843327','rec624843982','rec625268693','rec624844684','rec625268857','rec624844847','rec624845126','rec624845903','rec625272280','rec634682611','rec627014657','rec624848759'],
 'doctor':['rec622068228','rec622071430','rec625231581','rec622068230','rec622072180','rec622068236','rec622074083','rec622068231','rec623998768','rec624008368','rec622068242'],
 'articles':['rec626520317','rec626524092']
};
const heroImages={'about-clinic':'about-hero','technique':'technique-hero','profitable':'triple-hero','doctor':'doctor-hero','articles':'technique-hero','services':'services-hero'};
function originalHero(page){const r=source.pages[page].find(r=>r.atoms.some(a=>parseInt(a.size)>=40)&&r.text.includes('О клинике\nМетодика'));const text=r.atoms.filter(a=>!a.href&&a.text.trim());return '<section class="inner-hero shell source-page-hero page-'+page+'" data-source-record="'+r.id+'"><div><h1>'+E(text[0].text)+'</h1>'+text.slice(1).map(a=>paras(a.text)).join('')+button('#contact','Записаться на приём')+'</div><div class="inner-hero-art"><img src="/public/assets/'+heroImages[page]+'.webp" alt="Клиника ЭСТЕ" fetchpriority="high"></div></section>'}
function details(page){const ids=page==='technique'?['rec624337360','rec624340801','rec624342278','rec624343258','rec624344967']:page==='profitable'?['rec627796730']:page==='doctor'?['rec624027243']:[];return ids.length?'<section class="section shell source-details">'+ids.map((id,i)=>{const r=rec(page,id);return '<details data-source-record="'+id+'" id="detail-open'+(i?i+1:'')+'"><summary>'+E(r.atoms.find(a=>parseInt(a.size)>=40)?.text||'Подробнее')+arrow+'</summary>'+copy(r)+gallery(r)+'</details>'}).join('')+'</section>':''}
function pairedQuestion(page,titleId,answerId){const title=rec(page,titleId),answer=rec(page,answerId);return '<section class="source-question section shell" id="'+titleId+'"><div data-source-record="'+titleId+'"><h2>'+E(title.atoms.find(a=>parseInt(a.size)>=40).text)+'</h2></div><div class="question-answer" id="'+answerId+'" data-source-record="'+answerId+'">'+copy(answer)+'</div></section>'}
function pairedComparison(page,titleId,priceId){const title=rec(page,titleId),price=rec(page,priceId);return '<section class="source-price-section section shell" id="'+titleId+'"><div data-source-record="'+titleId+'"><h2>'+E(title.atoms.find(a=>parseInt(a.size)>=40).text)+'</h2></div><div id="'+priceId+'" data-source-record="'+priceId+'">'+profitableComparison(price)+'</div>'+gallery(price)+'</section>'}
function renderSections(page){const pairs={'rec624843327':'rec624843982','rec625268693':'rec624844684','rec625268857':'rec624844847'};const comparison='rec624845126';const skip=new Set(Object.values(pairs).concat('rec624845903'));return sections[page].map(id=>{if(page==='profitable'&&skip.has(id))return '';if(page==='profitable'&&pairs[id])return pairedQuestion(page,id,pairs[id]);if(page==='profitable'&&id===comparison)return pairedComparison(page,id,'rec624845903');return block(rec(page,id))}).join('')}
export function restoredContent(path){if(path==='/')return home();const page=path.slice(1);if(!sections[page])return null;return originalHero(page)+renderSections(page)+details(page)+(page==='about-clinic'?'<section class="section shell"><video class="source-video" controls preload="none" poster="/public/assets/room-light.webp"><source src="/public/assets/clinic-tour.mp4" type="video/mp4"></video></section>':'')}
export function bindSourceGalleries(){document.querySelectorAll('[data-gallery]').forEach(g=>{const track=g.querySelector('.source-gallery-track');const index=g.querySelector('[data-gallery-index]');const reduced=matchMedia('(prefers-reduced-motion: reduce)');const updateIndex=()=>{if(index){const first=track.querySelector('figure');const step=(first?.getBoundingClientRect().width||track.clientWidth)+16;index.textContent=String(Math.min(track.children.length,Math.round(track.scrollLeft/step)+1)).padStart(2,'0')}};track.addEventListener('scroll',updateIndex,{passive:true});g.querySelectorAll('[data-slide]').forEach(b=>b.addEventListener('click',()=>track.scrollBy({left:track.clientWidth*Number(b.dataset.slide),behavior:reduced.matches?'instant':'smooth'})));const toggle=g.querySelector('[data-autoplay-toggle]');if(!toggle)return;let timer,pausedByUser=false,visible=false;const pause=()=>{clearInterval(timer);timer=null};const play=()=>{if(timer||pausedByUser||reduced.matches||!visible||document.hidden||g.matches(':hover')||g.contains(document.activeElement))return;timer=setInterval(()=>{const end=track.scrollWidth-track.clientWidth;track.scrollTo({left:track.scrollLeft>=end-8?0:track.scrollLeft+track.clientWidth,behavior:'smooth'})},matchMedia('(max-width: 760px)').matches?3300:4200)};toggle.addEventListener('click',()=>{pausedByUser=!pausedByUser;toggle.setAttribute('aria-pressed',String(pausedByUser));toggle.setAttribute('aria-label',pausedByUser?'Возобновить автопрокрутку':'Остановить автопрокрутку');toggle.firstElementChild.textContent=pausedByUser?'▶':'Ⅱ';pausedByUser?pause():play()});const observer=new IntersectionObserver(entries=>{visible=entries[0].isIntersecting;visible?play():pause()},{threshold:.2});observer.observe(g);g.addEventListener('mouseenter',pause);g.addEventListener('mouseleave',play);g.addEventListener('focusin',pause);g.addEventListener('focusout',play);document.addEventListener('visibilitychange',()=>document.hidden?pause():play());reduced.addEventListener('change',()=>reduced.matches?pause():play())})}
export function bindHeroSpecialties(){const hero=document.querySelector('.route-home .original-specialties');if(!hero)return;const label=hero.querySelector('[data-specialty-text]'),toggle=hero.querySelector('.specialty-toggle'),reduced=matchMedia('(prefers-reduced-motion: reduce)');const names=['Стоматология','Ортодонтия','Остеопатия'];let index=0,position=names[0].length,deleting=false,timer,visible=true,paused=false;const stop=()=>{clearTimeout(timer);timer=null};const step=()=>{if(paused||!visible||document.hidden||reduced.matches)return;const word=names[index];if(!deleting&&position<word.length){position++;label.textContent=word.slice(0,position);timer=setTimeout(step,105);return}if(!deleting){deleting=true;timer=setTimeout(step,1850);return}if(position>0){position--;label.textContent=word.slice(0,position);timer=setTimeout(step,55);return}index=(index+1)%names.length;deleting=false;timer=setTimeout(step,320)};const resume=()=>{stop();if(!paused&&visible&&!document.hidden&&!reduced.matches)timer=setTimeout(step,220)};toggle.addEventListener('click',()=>{paused=!paused;toggle.setAttribute('aria-pressed',String(paused));toggle.setAttribute('aria-label',paused?'Возобновить смену направлений':'Остановить смену направлений');toggle.textContent=paused?'▶':'Ⅱ';paused?stop():resume()});new IntersectionObserver(([entry])=>{visible=entry.isIntersecting;visible?resume():stop()},{threshold:.1}).observe(hero);document.addEventListener('visibilitychange',resume);reduced.addEventListener('change',()=>{if(reduced.matches){stop();label.textContent=names.join(' · ');toggle.hidden=true}else{label.textContent=names[index];position=names[index].length;toggle.hidden=false;resume()}});if(reduced.matches){label.textContent=names.join(' · ');toggle.hidden=true}else resume()}
export function bindClinicFilm(){const section=document.querySelector('.route-home .clinic-film');if(!section)return;const video=section.querySelector('video');const button=section.querySelector('.film-toggle');const reduced=matchMedia('(prefers-reduced-motion: reduce)');let userPaused=false;const sync=()=>{const playing=!video.paused;button.setAttribute('aria-label',playing?'Приостановить видео':'Воспроизвести видео');button.firstChild.textContent=playing?'Остановить видео ':'Смотреть видео '};const play=()=>{if(reduced.matches||document.hidden||userPaused)return;video.play().catch(()=>{}).finally(sync)};const observer=new IntersectionObserver(([entry])=>entry.isIntersecting?play():video.pause(),{threshold:.25});observer.observe(section);button.addEventListener('click',()=>{userPaused=!video.paused;if(video.paused){userPaused=false;video.play().catch(()=>{}).finally(sync)}else{video.pause();sync()}});video.addEventListener('play',sync);video.addEventListener('pause',sync);document.addEventListener('visibilitychange',()=>document.hidden?video.pause():play());reduced.addEventListener('change',()=>reduced.matches?video.pause():play());sync()}
export {originalHero};
export function restoredServiceTail(){return ['rec624822675','rec624826019','rec624834535','rec624835656','rec625263103','rec625261042','rec627014195','rec625261741'].map(id=>block(rec('services',id))).join('')}
document.addEventListener('click',e=>{const a=e.target.closest('a[href^="#detail-"]');if(a){const d=document.getElementById(a.hash.slice(1));if(d)d.open=true}});
