// Original clinic content is kept separately from layout; editorial proposals are mapped by record.
// Copy rollback: render the captured clinic text, never editorial proposals.
const heroCopy={},blockCopy={};
import {specialistReviews} from './review-data.js';
const source=await fetch('/st-kids/public/data/source-pages.json').then(r=>r.json());
export const typesetRussian=s=>{
 let value=String(s).replaceAll('₽','Р').replace(/(?<=[А-Яа-яЁё])-(?=[А-Яа-яЁё])/g,'‑');
 const small=/(^|[\s([{«„])((?:в|во|с|со|к|ко|у|о|об|обо|на|за|из|от|до|по|при|для|без|над|под|про|и|а|но|не)) ([А-Яа-яЁё])/giu;
 let before;do{before=value;value=value.replace(small,'$1$2\u00a0$3')}while(value!==before);
 return value;
};
const E=s=>typesetRussian(s).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');
const arrow='<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M4 12h15m-6-6 6 6-6 6" fill="none" stroke="currentColor" stroke-width="1.7"/></svg>';
const unique=a=>a.filter((x,i)=>a.findIndex(y=>y.text===x.text)===i);
const rec=(page,id)=>source.pages[page].find(r=>r.id===id);
const img=(im,alt='',cls='',loading='lazy')=>'<img class="'+cls+'" src="'+source.assets[im.url]+'" alt="'+E(alt)+'" loading="'+loading+'" decoding="async">';
const target=h=>h?.startsWith('#popup:')?'#contact':h?.startsWith('#open')?'#detail-'+h.slice(1):h;
const button=(h,t,c='')=>'<a class="button '+c+'" href="'+E(target(h)||'#contact')+'"><span>'+E(t)+'</span>'+arrow+'</a>';
// Emphasize only verified phrases from the original copy; the wording stays intact.
const emphasisByRecord={
 rec622022822:['агрессивным ортодонтическим лечением','организм человека не всегда безобидно на них реагирует'],
 rec626995065:['80% наших пациентов - дети и подростки','положительный опыт общения','АДАПТАЦИОННЫЙ ПРИЕМ-знакомство','снимать стресс в игре'],
 rec622025102:['осмотр и консультацию сразу трех специалистов по цене одного'],
 rec622031542:['закрепить его без агрессивного вреда и стресса'],
 rec622040175:['сотрудничество между врачом и клиентом рождается в ДОВЕРИИ'],
 rec622049173:['диагностики зубочелюстной системы в комплексе','без вреда пациенту'],
 rec622050389:['врачебное мнение','на основании нашей статистики и результатов диагностики'],
 rec627003393:['80% наших пациентов - дети и подростки','адаптационный прием-знакомство','снимать стресс в игре'],
 rec624044039:['дискомфорт и боль','нарушаем функции организма'],
 rec624065448:['мягко и эффективно работать над эстетикой улыбки','ОСТЕОПАТИЧЕСКОЕ СОПРОВОЖДЕНИЕ АДАПТИРУЕТ ТКАНИ К ИЗМЕНЕНИЯМ'],
 rec624843982:['системные рекомендации','без комплексной диагностики на входе'],
 rec622068228:['закрепить его без агрессивного вреда и стресса'],
 rec626524092:['исключительно с разрешения наших клиентов','истории неуспеха']
};
const paras=(t,id)=>(id==='rec624843982'&&t.startsWith('Все в нашем организме')?t.replace('. Если ','.\nЕсли '):t).trim().split(/\n+/).filter(Boolean).map(p=>{
 let html=E(p);
 for(const phrase of emphasisByRecord[id]||[])html=html.replaceAll(E(phrase),'<strong>'+E(phrase)+'</strong>');
 return '<p>'+html+'</p>';
}).join('');
function editorialCopy(r,includeHeading=true){
 const c=blockCopy[r.id];if(!c)return null;
 const points=c.points?'<div class="audit-points">'+c.points.map(([title,body])=>'<article><h3>'+E(title)+'</h3><p>'+E(body)+'</p></article>').join('')+'</div>':'';
 const facts=c.facts?'<div class="audit-facts">'+c.facts.map(f=>'<p>'+E(f)+'</p>').join('')+'</div>':'';
 const detail=c.preserveDetails?'<details class="audit-source-detail"><summary>Какие ситуации описаны на сайте клиники</summary>'+paras(r.atoms.filter(a=>parseInt(a.size)<40&&!a.href).map(a=>a.text).join('\n'),r.id)+'</details>':'';
 return (includeHeading?'<h2>'+E(c.title)+'</h2>':'')+'<div class="audit-prose">'+(c.paragraphs||[]).map(p=>'<p>'+E(p)+'</p>').join('')+'</div>'+points+facts+detail+(c.action?'<div class="source-actions">'+button(c.action[1],c.action[0])+'</div>':'');
}
function photos(r){return r.images.filter((im,i,a)=>!/\.svg/.test(im.url)&&a.findIndex(x=>x.url===im.url)===i)}
function gallery(r){const media=photos(r),slides=media.filter(im=>im.class.includes('slds'));const displacedPortraits=['rec622031542','rec624840701','rec624826019','rec622068228'].includes(r.id)?media.filter(im=>!im.class.includes('slds')):[];const all=slides.length>1?[...slides.slice(1),slides[0],...displacedPortraits]:media;if(!all.length)return '';const topic=r.atoms.find(a=>parseInt(a.size)>=40)?.text.trim()||'клиники ЭСТЕ';const auto=all.length>1;return '<div class="source-gallery" data-gallery><div class="source-gallery-track" tabindex="0" aria-label="Фотографии: '+E(topic)+'. Прокручивайте вбок">'+all.map((im,i)=>'<figure>'+img(im,im.alt||'Фото '+(i+1)+' из '+all.length+': '+topic,'',i===0&&source.pages.home.includes(r)?'eager':'lazy')+'</figure>').join('')+'</div>'+(all.length>1?'<div class="gallery-controls"><span class="gallery-count"><b data-gallery-index>01</b> / '+String(all.length).padStart(2,'0')+'</span>'+(auto?'<button type="button" class="gallery-pause" data-autoplay-toggle aria-pressed="false" aria-label="Остановить автопрокрутку"><span aria-hidden="true">Ⅱ</span></button>':'')+'<button type="button" data-slide="-1" aria-label="Предыдущее фото">'+arrow+'</button><button type="button" data-slide="1" aria-label="Следующее фото">'+arrow+'</button></div>':'')+'</div>'}
function copy(r){const replacement=editorialCopy(r);if(replacement)return replacement;const a=unique(r.atoms.filter(x=>x.text.trim()&&!/^[<>]$/.test(x.text.trim())));const ctas=a.filter(x=>x.href&&parseInt(x.size)===24||x.href&&/^(ВСЕ УСЛУГИ|ЗАПИСАТЬСЯ)/.test(x.text)||r.id==='rec625263103'&&x.text.trim()==='ЗАПИСАТЬСЯ');const experience=r.atoms.find(x=>x.text.startsWith('Уже 17 лет'));const body=a.filter(x=>!ctas.includes(x)&&x!==experience);const main=body.find(x=>parseInt(x.size)>=40);let html=main?'<h2>'+E(main.text.trim())+'</h2>':'';
 const rest=body.filter(x=>x!==main);const ordered=[...rest].sort((a,b)=>a.top-b.top||a.left-b.left);let groups=[];
 const headings=ordered.filter(a=>parseInt(a.size)>=24);groups=headings.map(a=>({heading:a.text,anchor:a,items:[]}));
 for(const item of ordered.filter(a=>!headings.includes(a))){const candidates=groups.filter(g=>g.anchor&&g.anchor.top<=item.top+3).sort((a,b)=>(Math.abs(a.anchor.left-item.left)*3+Math.abs(a.anchor.top-item.top))-(Math.abs(b.anchor.left-item.left)*3+Math.abs(b.anchor.top-item.top)));if(candidates.length)candidates[0].items.push(item);else{let intro=groups.find(g=>!g.anchor);if(!intro){intro={heading:'',items:[]};groups.unshift(intro)}intro.items.push(item)}}
 html+='<div class="source-copy-groups '+(groups.length>1?'multiple':'')+'">'+groups.map(g=>'<div>'+(g.heading?'<h3>'+E(g.heading.trim())+'</h3>':'')+g.items.map(a=>paras(a.text,r.id)).join('')+'</div>').join('')+'</div>';
 if(experience)html+='<aside class="experience-callout"><p>'+E(experience.text).replace('17 лет','<strong>17 лет</strong>')+'</p></aside>';
 html+='<div class="source-actions">'+ctas.map(a=>button(a.href,a.text)).join('')+'</div>';return html;
}
function profitableComparison(r){return '<div class="comparison-layout"><div class="market-price"><h3>'+E(r.atoms[6].text)+'</h3><p>'+E(r.atoms[7].text)+'</p><s>'+E(r.atoms[8].text)+'</s></div><div class="clinic-offer"><div class="clinic-price"><h3>'+E(r.atoms[9].text)+'</h3><strong>'+E(r.atoms[11].text)+'</strong><span>'+E(r.atoms[10].text)+'</span></div></div></div><div class="source-actions">'+button(r.atoms[0].href,r.atoms[0].text)+'</div>'}
function profitableBenefits(r){const notes=['ЭКОНОМИЯ ВРЕМЕНИ','ЗАПАТЕНТОВАННАЯ МЕТОДИКА'].map((title,i)=>{const atom=r.atoms.find(x=>x.text===title),body=r.atoms.find(x=>parseInt(x.size)===20&&x.left===atom.left&&x.top>atom.top);return '<article class="comparison-note"><h3>'+E(title)+'</h3>'+paras(body.text,r.id)+motif(i?'clover':'bird')+'</article>'}).join('');return '<section class="profit-benefits section shell" aria-label="Преимущества комплексного осмотра"><div class="comparison-notes">'+notes+'</div></section>'}
function teamCards(r){const staff=[['ЕЛЕНА СЕСЁЛКИНА','Главный врач, ортодонт-остеопат, доктор остеопатии, специалист P-DTR, автор патента',0],['ВАСИЛИЙ ЛАПА','Врач-ортодонт высшей категории',3],['НАТАЛЬЯ ВИКУЛОВА','Стоматолог-терапевт высшей категории',2],['НАТАЛЬЯ БЛАШЕНКОВА','Куратор лечения',1]];const portraits=photos(r);const profitable=r.id==='rec634682611';return '<section class="source-team section shell" id="'+r.id+'" data-source-record="'+r.id+'" aria-label="Специалисты клиники ЭСТЕ">'+''+'<div class="team-cards">'+staff.map(([name,role,portrait])=>'<figure class="team-card">'+img(portraits[portrait],name,'','lazy')+'<figcaption><h3>'+E(name)+'</h3><p>'+E(role)+'</p></figcaption></figure>').join('')+'</div><div class="source-actions">'+button('#contact',r.atoms.find(a=>a.text.trim()==='ЗАПИСАТЬСЯ')?.text||'ЗАПИСАТЬСЯ')+'</div></section>'}
function protocolCards(r){const heading=r.atoms.find(a=>parseInt(a.size)>=40),statements=r.atoms.find(a=>parseInt(a.size)===20).text.split(/\n+/).filter(t=>t.trim());return '<section class="source-protocols section shell" id="'+r.id+'" data-source-record="'+r.id+'"><div class="protocol-heading"><h2>'+E(heading.text)+'</h2>'+motif('clover')+'</div><div class="protocol-grid">'+statements.map(body=>'<article>'+paras(body,r.id)+'</article>').join('')+'<a class="protocol-doc-link" href="#rec622055204">ЛИЦЕНЗИИ * СЕРТИФИКАТЫ * ПАТЕНТ ЭСТЕ '+arrow+'</a></div>'+gallery(r)+'</section>'}
function trustBlock(r){const a=r.atoms.filter(a=>!a.href&&a.text.trim()),heading=a.find(a=>parseInt(a.size)>=40),prose=a.filter(a=>parseInt(a.size)===20),lines=prose[1].text.split(/\n+/).map(t=>t.trim()).filter(Boolean);return '<section class="source-trust section shell" id="'+r.id+'" data-source-record="'+r.id+'"><div class="trust-content"><div class="trust-intro"><h2>'+E(heading.text)+'</h2>'+paras(prose[0].text,r.id)+paras(lines[0],r.id)+'<ul class="trust-questions">'+lines.slice(1).map(t=>'<li>'+E(t)+'</li>').join('')+'</ul></div></div>'+gallery(r)+'</section>'}
function adaptationBlock(r){return '<section class="adaptation-section section shell" id="'+r.id+'" data-source-record="'+r.id+'"><div class="adaptation-copy">'+copy(r)+'</div>'+gallery(r)+'</section>'}
function firstVisitBlock(r){return '<section class="first-visit-section section shell" id="'+r.id+'" data-source-record="'+r.id+'"><div class="first-visit-copy">'+copy(r)+motif('heart')+'</div>'+gallery(r)+'</section>'}
function signatureBlock(r){const media=photos(r),doctor=media.find(im=>source.assets[im.url]?.includes('41c27ebbb17f'))||media[0],child=media.find(im=>source.assets[im.url]?.includes('2ef92752da39'))||media.find(im=>im!==doctor),caption=r.atoms.find(a=>a.text==='Главный врач клиники'),body={...r,atoms:r.atoms.filter(a=>a!==caption)};return '<section class="signature-section section shell" id="'+r.id+'" data-source-record="'+r.id+'"><div class="signature-copy">'+copy(body)+'<div class="signature-doctor">'+img(doctor,'Главный врач клиники ЭСТЕ','signature-avatar')+'<span>'+E(caption.text)+'</span></div></div><div class="signature-portrait">'+img(child,'Ребёнок с моделью челюсти','signature-boy')+'</div></section>'}
function examinationBlock(r){const pairs=[[8,9],[0,1],[2,3],[4,5],[6,7]];const why=['Помогает понять особенности прикуса до выбора аппарата.','Помогает учесть состояние опорно-двигательной системы при планировании лечения.','Даёт дополнительные данные о положении тела, если исследование показано.','Позволяет подобрать способ коррекции по итогам обследования.','Помогает сопровождать изменения во время и после основного этапа лечения.'];return '<section class="source-examination section shell" id="'+r.id+'" data-source-record="'+r.id+'"><div class="examination-list">'+pairs.map(([h,p],i)=>'<details class="examination-step" '+(i===0?'open':'')+'><summary><span class="examination-number">0'+(i+1)+'</span><span>'+E(r.atoms[h].text)+'</span><span aria-hidden="true">＋</span></summary><div class="examination-body"><p class="examination-why">'+E(why[i])+'</p>'+paras(r.atoms[p].text,r.id)+'</div></details>').join('')+'<div class="source-actions">'+button(r.atoms[10].href||'/services',r.atoms[10].text)+'</div></div>'+gallery(r)+'</section>'}
function orthodontistBlock(r){const heading=r.atoms[0].text;const sentences=r.atoms[1].text.split(/(?<=\.)\s+(?=[А-Я])/).filter(Boolean);return '<section class="source-orthodontist section shell" id="'+r.id+'" data-source-record="'+r.id+'"><div class="orthodontist-copy"><h2>'+E(heading)+'</h2><div class="orthodontist-points">'+sentences.map(s=>'<p>'+E(s)+'</p>').join('')+'</div></div>'+gallery(r)+'</section>'}
function serviceCallout(r){const a=r.atoms;return '<section class="source-service-callout section shell" id="'+r.id+'" data-source-record="'+r.id+'"><div><h2>'+E(a.find(x=>parseInt(x.size)>=40&&x.text!=='5000₽').text)+'</h2><p>'+E(a.find(x=>x.text.startsWith('СТОИМОСТЬ')).text)+'</p><strong>5&nbsp;000&nbsp;Р</strong></div><div class="source-actions">'+button('#contact','ЗАПИСАТЬСЯ')+'</div>'+motif('bird')+gallery(r)+'</section>'}
function motif(shape){return '<span class="motif motif-'+shape+'" aria-hidden="true"></span>'}
function clinicServices(r){const kinds=['heart','clover','bird'];const items=[[2,3],[4,5],[6,7]];return '<section class="clinic-service-overview section shell" id="'+r.id+'" data-source-record="'+r.id+'"><div class="clinic-service-grid">'+items.map(([h,b],i)=>'<article class="clinic-service-card"><h3>'+E(r.atoms[h].text)+'</h3><ul>'+r.atoms[b].text.split(/\n+/).filter(Boolean).map(t=>'<li>'+E(t)+'</li>').join('')+'</ul>'+motif(kinds[i])+'</article>').join('')+'</div><div class="source-actions">'+button('/services','ВСЕ УСЛУГИ')+'</div></section>'}
function applianceChoices(r){const logos=r.images.slice(1).map((im,i)=>'<li class="appliance-logo appliance-logo-'+i+'">'+img(im,['Invisalign','Spark','3D Smile','StarSmile','FlexiLigner','Ортодонтический аппарат','Корректор'][i])+'</li>').join('');return '<section class="appliance-choice section shell" id="'+r.id+'" data-source-record="'+r.id+'"><div class="appliance-logos"><ul aria-label="Системы ортодонтических аппаратов">'+logos+'</ul></div><div class="appliance-copy"><h2>'+E(r.atoms[1].text)+'</h2>'+paras(r.atoms[2].text,r.id)+'<div class="source-actions">'+button('#contact',r.atoms[0].text)+'</div></div></section>'}
function methodCards(r){const pairs=[[8,9,7,'clover'],[0,1,9,'heart'],[2,3,11,'heart'],[4,5,13,'clover'],[6,7,15,'clover']];return '<section class="method-service-section section shell" id="'+r.id+'" data-source-record="'+r.id+'"><div class="method-service-grid">'+pairs.map(([h,b,imageIndex,shape])=>'<article class="method-service-card"><h3>'+E(r.atoms[h].text)+'</h3>'+paras(r.atoms[b].text,r.id)+'<div class="method-motif motif-'+shape+'">'+img(r.images[imageIndex],r.atoms[h].text)+'</div></article>').join('')+'</div><div class="source-actions">'+button('/services','ВСЕ УСЛУГИ')+'</div></section>'}
function giftBlock(r){return '<section class="gift-section section shell" id="'+r.id+'" data-source-record="'+r.id+'"><div class="gift-photo">'+img(r.images[0],'Ребёнок в клинике ЭСТЕ')+'</div><div class="gift-copy"><h2>'+E(r.atoms[0].text)+'</h2><p>'+E(r.atoms[1].text)+'</p><div class="gift-price"><s>'+E(r.atoms[2].text)+'</s></div><div class="source-actions">'+button('#contact','Записаться')+'</div><a class="gift-detail" href="#detail-open">'+E(r.atoms[4].text)+' '+arrow+'</a></div></section>'}
function yandexBlock(r){const review=photos(r)[0];const quotes=[['Любовь Козырева','1 декабря 2022','Приветливый персонал, качественная работа, делали зубы дочери, во сне. Всё прекрасно и без стресса.'],['Анна Новикова','25 июня 2023','Очень хорошо, прохожу программу элайнеров, есть в сопровождении остеопатия']];return '<section class="yandex-section section shell" id="'+r.id+'" data-source-record="'+r.id+'"><div class="yandex-intro"><h2>'+E(r.atoms[1].text)+'</h2><p>'+E(r.atoms[2].text)+'</p><img class="yandex-award" src="/public/assets/source/66cfb6c2386c.svg" alt="Награда Яндекса «Хорошее место» на сохранённом снимке 2022 года" loading="lazy"><div class="yandex-review-cards">'+quotes.map(([name,date,quote])=>'<figure class="yandex-review"><blockquote>«'+E(quote)+'»</blockquote><figcaption>'+E(name)+' · '+E(date)+'</figcaption></figure>').join('')+'</div><div class="source-actions">'+button(r.atoms[0].href,r.atoms[0].text)+'</div></div><figure class="yandex-source">'+img(review,'Снимок отзывов клиники ЭСТЕ в Яндексе','','eager')+'</figure></section>'}
function specialistReviewsIntro(r){return '<span class="specialist-review-anchor" id="'+r.id+'" data-source-record="'+r.id+'" aria-hidden="true"></span>'}
function specialistReviewsBlock(r){return '<section class="specialist-review-section section shell" id="'+r.id+'" data-source-record="'+r.id+'" data-specialist-reviews aria-label="Отзывы о специалистах ЭСТЕ"><div class="specialist-review-heading"><h2>Отзывы о специалистах ЭСТЕ</h2><div class="specialist-review-controls"><span aria-live="polite"><b data-review-position>01</b> / '+String(specialistReviews.length).padStart(2,'0')+'</span><div><button type="button" data-review-step="-1" aria-label="Предыдущий отзыв">'+arrow+'</button><button type="button" data-review-step="1" aria-label="Следующий отзыв">'+arrow+'</button></div></div></div><div class="specialist-review-stage" tabindex="0" aria-label="Отзывы о специалистах. Прокручивайте вбок">'+specialistReviews.map((review,i)=>'<article class="specialist-review-story" data-review-story><div class="review-image-scroll" tabindex="0" aria-label="Исходный отзыв: '+E(review.subject)+'"><img src="/public/assets/source/'+E(review.source)+'" alt="'+E(review.subject)+', '+E(review.date)+'" loading="lazy"></div><div class="review-accessible-copy"><p>'+E(review.body)+'</p><p>Ответ клиники: '+E(review.response)+'</p></div></article>').join('')+'</div></section>'}
function examRolesBlock(r){return trustBlock(r).replace('source-trust section shell','source-trust exam-roles-section section shell')}
function block(r){if(r.id==='rec622036080')return clinicServices(r);if(r.id==='rec622050389')return applianceChoices(r);if(r.id==='rec624075708')return methodCards(r);if(r.id==='rec624848759')return giftBlock(r);if(r.id==='rec622060036')return yandexBlock(r);if(r.id==='rec622061458')return specialistReviewsIntro(r);if(r.id==='rec622061536')return specialistReviewsBlock(r);if(r.id==='rec625272280')return examRolesBlock(r);if(['rec622041249','rec634682611'].includes(r.id))return teamCards(r);if(r.id==='rec622049173')return protocolCards(r);if(r.id==='rec622040175')return trustBlock(r);if(['rec626995065','rec627003393','rec627012913','rec627014657','rec627014195'].includes(r.id))return adaptationBlock(r);if(['rec622025102','rec625232442','rec625253182','rec622068242','rec625261741'].includes(r.id))return firstVisitBlock(r);if(r.id==='rec624065448')return signatureBlock(r);if(r.id==='rec624062019'&&!blockCopy[r.id])return orthodontistBlock(r);if(r.id==='rec625263103')return serviceCallout(r);const media=photos(r),hasSlides=media.some(im=>im.class.includes('slds')),portraits=hasSlides&&!['rec622031542','rec624840701','rec624826019','rec622068228'].includes(r.id)?media.filter(im=>!im.class.includes('slds')):[];const hasCopy=r.atoms.some(a=>a.text.trim()&&!/^[<>]$/.test(a.text.trim()));if(!hasCopy&&media.length)return '<section class="source-section section shell media-only" id="'+r.id+'" data-source-record="'+r.id+'">'+gallery(r)+'</section>';const benefits=r.id==='rec624845903'?profitableComparison(r):copy(r);return '<section class="source-section section shell '+(media.length?'has-media':'')+'" id="'+r.id+'" data-source-record="'+r.id+'"><div class="source-copy">'+benefits+(portraits.length?'<div class="source-portraits">'+portraits.map(im=>img(im,'Специалисты клиники ЭСТЕ')).join('')+'</div>':'')+'</div>'+gallery(r)+'</section>'}
function directory(){const r=rec('home','rec622016700'),p=photos(r),entries=unique(r.atoms).filter(a=>parseInt(a.size)>=40);return '<section class="section shell source-directory" aria-label="Разделы сайта" data-source-record="'+r.id+'">'+entries.slice(0,5).map((a,i)=>'<a class="directory-entry" href="'+a.href+'"><div><h2>'+E(a.text)+'</h2>'+paras(r.atoms.find(x=>x.href===a.href&&parseInt(x.size)===20).text)+'<span class="directory-arrow">'+arrow+'</span></div><div class="brand-photo directory-photo-'+i+' '+(i%2?'bird-photo':'clover-photo')+'" style="--photo:url('+source.assets[p[i].url]+')" role="img" aria-label="'+E(a.text)+'"></div></a>').join('')+'<a class="directory-last" href="/doctor"><span>'+E(entries[5].text)+'</span>'+arrow+'</a></section>'}
function clinicVideo(){return '<section class="clinic-film section shell" aria-labelledby="clinic-film-title"><video class="source-video" muted loop playsinline preload="none" poster="/public/assets/room-light.webp"><source src="/public/assets/clinic-tour.mp4" type="video/mp4">Ваш браузер не поддерживает воспроизведение видео.</video><div class="clinic-film-copy"><h2 id="clinic-film-title">Видео о клинике</h2><button class="film-toggle" type="button" aria-label="Воспроизвести видео">Смотреть видео</button></div></section>'}
function journey(){return ''}
function home(){return '<section class="home-hero shell original-hero audit-hero restored-brand-hero"><div class="hero-content"><h1 class="hero-mark">ЭСТЕ</h1><div class="original-specialties" aria-label="Стоматология, ортодонтия, остеопатия"><span class="specialty-text" data-specialty-text>Стоматология</span><i class="specialty-caret" aria-hidden="true"></i><button type="button" class="specialty-toggle" aria-label="Остановить смену направлений" aria-pressed="false">Ⅱ</button></div><div class="hero-actions">'+button('#contact','ЗАПИСАТЬСЯ')+button('/technique','БОЛЬШЕ О МЕТОДИКЕ','button-outline')+'</div></div><div class="hero-art"><img src="/public/assets/hero-main.webp" alt="ЭСТЕ — стоматология, ортодонтия, остеопатия" fetchpriority="high"></div></section>'+block(rec('home','rec622009100'))+block(rec('home','rec622015033'))+directory()+block(rec('home','rec622022822'))+clinicVideo()+block(rec('home','rec626995065'))+block(rec('home','rec622025102'))}
const sections={
 'about-clinic':['rec622031542','rec625193524','rec630123451','rec622036080','rec622040175','rec622041249','rec622049173','rec622050389','rec622054959','rec622055204','rec622055876','rec622060036','rec622061458','rec622061536','rec627003393','rec625232442'],
 'technique':['rec624044039','rec624062019','rec624063674','rec624065448','rec624073439','rec624074967','rec624075708','rec627012913','rec625253182'],
 'profitable':['rec624840701','rec624841252','rec624843327','rec624843982','rec625268693','rec624844684','rec625268857','rec624844847','rec624845126','rec624845903','rec625272280','rec634682611','rec627014657','rec624848759'],
 'doctor':['rec622068228','rec622071430','rec625231581','rec622068230','rec622072180','rec622068236','rec622074083','rec622068231','rec623998768','rec624008368','rec622068242'],
 'articles':['rec626520317','rec626524092']
};
const heroImages={'about-clinic':'about-hero','technique':'technique-hero','profitable':'triple-hero','doctor':'doctor-hero','articles':'technique-hero','services':'services-hero'};
function originalHero(page){const r=source.pages[page].find(r=>r.atoms.some(a=>parseInt(a.size)>=40)&&r.text.includes('О клинике\nМетодика'));const text=r.atoms.filter(a=>!a.href&&a.text.trim());return '<section class="inner-hero shell source-page-hero page-'+page+'" data-source-record="'+r.id+'"><div><h1>'+E(text[0].text)+'</h1>'+text.slice(1).map(a=>paras(a.text)).join('')+button('#contact','ЗАПИСАТЬСЯ')+'</div><div class="inner-hero-art"><img src="/public/assets/'+heroImages[page]+'.webp" alt="Клиника ЭСТЕ" fetchpriority="high"></div></section>'}
function details(page){const ids=page==='technique'?['rec624337360','rec624340801','rec624342278','rec624343258','rec624344967']:page==='profitable'?['rec627796730']:page==='doctor'?['rec624027243']:[];return ids.length?'<section class="section shell source-details">'+ids.map((id,i)=>{const r=rec(page,id);return '<details data-source-record="'+id+'" id="detail-open'+(i?i+1:'')+'"><summary>'+E(r.atoms.find(a=>parseInt(a.size)>=40)?.text||'Подробнее')+arrow+'</summary>'+copy(r)+gallery(r)+'</details>'}).join('')+'</section>':''}
function pairedQuestion(page,titleId,answerId){const title=rec(page,titleId),answer=rec(page,answerId);return '<section class="source-question section shell" id="'+titleId+'"><div class="question-heading" data-source-record="'+titleId+'"><h2>'+E(title.atoms.find(a=>parseInt(a.size)>=40).text)+'</h2></div><div class="question-answer" id="'+answerId+'" data-source-record="'+answerId+'">'+copy(answer)+'</div></section>'}
function pairedComparison(page,titleId,priceId){const price=rec(page,priceId),title=rec(page,titleId);return '<section class="source-price-section section shell" id="'+titleId+'"><div data-source-record="'+titleId+'"><h2>'+E(title.atoms.find(a=>parseInt(a.size)>=40).text)+'</h2></div><div id="'+priceId+'" data-source-record="'+priceId+'">'+profitableComparison(price)+'</div></section>'+profitableBenefits(price)}
function renderSections(page){const pairs={'rec624843327':'rec624843982','rec625268693':'rec624844684','rec625268857':'rec624844847'};const comparison='rec624845126';const skip=new Set(Object.values(pairs).concat('rec624845903'));return sections[page].map(id=>{if(page==='profitable'&&skip.has(id))return '';if(page==='profitable'&&pairs[id])return pairedQuestion(page,id,pairs[id]);if(page==='profitable'&&id===comparison)return pairedComparison(page,id,'rec624845903');return block(rec(page,id))}).join('')}
export function restoredContent(path){if(path==='/')return home();const page=path.slice(1);if(!sections[page])return null;return originalHero(page)+renderSections(page)+details(page)+(page==='about-clinic'?'<section class="section shell"><video class="source-video" controls preload="none" poster="/public/assets/room-light.webp"><source src="/public/assets/clinic-tour.mp4" type="video/mp4"></video></section>':'')}
export function bindSourceGalleries(){document.querySelectorAll('[data-gallery]').forEach(g=>{const track=g.querySelector('.source-gallery-track');const index=g.querySelector('[data-gallery-index]');const reduced=matchMedia('(prefers-reduced-motion: reduce)');const updateIndex=()=>{if(index){const first=track.querySelector('figure');const step=(first?.getBoundingClientRect().width||track.clientWidth)+16;index.textContent=String(Math.min(track.children.length,Math.round(track.scrollLeft/step)+1)).padStart(2,'0')}};track.addEventListener('scroll',updateIndex,{passive:true});g.querySelectorAll('[data-slide]').forEach(b=>b.addEventListener('click',()=>track.scrollBy({left:track.clientWidth*Number(b.dataset.slide),behavior:reduced.matches?'instant':'smooth'})));const toggle=g.querySelector('[data-autoplay-toggle]');if(!toggle)return;let timer,pausedByUser=false,visible=false;const pause=()=>{clearInterval(timer);timer=null};const play=()=>{if(timer||pausedByUser||reduced.matches||!visible||document.hidden||g.matches(':hover')||g.contains(document.activeElement))return;timer=setInterval(()=>{const end=track.scrollWidth-track.clientWidth;track.scrollTo({left:track.scrollLeft>=end-8?0:track.scrollLeft+track.clientWidth,behavior:'smooth'})},matchMedia('(max-width: 760px)').matches?3300:4200)};toggle.addEventListener('click',()=>{pausedByUser=!pausedByUser;toggle.setAttribute('aria-pressed',String(pausedByUser));toggle.setAttribute('aria-label',pausedByUser?'Возобновить автопрокрутку':'Остановить автопрокрутку');toggle.firstElementChild.textContent=pausedByUser?'▶':'Ⅱ';pausedByUser?pause():play()});const observer=new IntersectionObserver(entries=>{visible=entries[0].isIntersecting;visible?play():pause()},{threshold:.2});observer.observe(g);g.addEventListener('mouseenter',pause);g.addEventListener('mouseleave',play);g.addEventListener('focusin',pause);g.addEventListener('focusout',play);document.addEventListener('visibilitychange',()=>document.hidden?pause():play());reduced.addEventListener('change',()=>reduced.matches?pause():play())})}
export function bindHeroSpecialties(){const hero=document.querySelector('.route-home .original-specialties');if(!hero)return;const label=hero.querySelector('[data-specialty-text]'),toggle=hero.querySelector('.specialty-toggle'),reduced=matchMedia('(prefers-reduced-motion: reduce)');const names=['Стоматология','Ортодонтия','Остеопатия'];let index=0,position=names[0].length,deleting=false,timer,visible=true,paused=false;const stop=()=>{clearTimeout(timer);timer=null};const step=()=>{if(paused||!visible||document.hidden||reduced.matches)return;const word=names[index];if(!deleting&&position<word.length){position++;label.textContent=word.slice(0,position);timer=setTimeout(step,105);return}if(!deleting){deleting=true;timer=setTimeout(step,1850);return}if(position>0){position--;label.textContent=word.slice(0,position);timer=setTimeout(step,55);return}index=(index+1)%names.length;deleting=false;timer=setTimeout(step,320)};const resume=()=>{stop();if(!paused&&visible&&!document.hidden&&!reduced.matches)timer=setTimeout(step,220)};toggle.addEventListener('click',()=>{paused=!paused;toggle.setAttribute('aria-pressed',String(paused));toggle.setAttribute('aria-label',paused?'Возобновить смену направлений':'Остановить смену направлений');toggle.textContent=paused?'▶':'Ⅱ';paused?stop():resume()});new IntersectionObserver(([entry])=>{visible=entry.isIntersecting;visible?resume():stop()},{threshold:.1}).observe(hero);document.addEventListener('visibilitychange',resume);reduced.addEventListener('change',()=>{if(reduced.matches){stop();label.textContent=names.join(' · ');toggle.hidden=true}else{label.textContent=names[index];position=names[index].length;toggle.hidden=false;resume()}});if(reduced.matches){label.textContent=names.join(' · ');toggle.hidden=true}else resume()}
export function bindClinicFilm(){const section=document.querySelector('.route-home .clinic-film');if(!section)return;const video=section.querySelector('video');const button=section.querySelector('.film-toggle');const reduced=matchMedia('(prefers-reduced-motion: reduce)');let userPaused=false;const sync=()=>{const playing=!video.paused;button.setAttribute('aria-label',playing?'Приостановить видео':'Воспроизвести видео');button.firstChild.textContent=playing?'Остановить видео ':'Смотреть видео '};const play=()=>{if(reduced.matches||document.hidden||userPaused)return;video.play().catch(()=>{}).finally(sync)};const observer=new IntersectionObserver(([entry])=>entry.isIntersecting?play():video.pause(),{threshold:.25});observer.observe(section);button.addEventListener('click',()=>{userPaused=!video.paused;if(video.paused){userPaused=false;video.play().catch(()=>{}).finally(sync)}else{video.pause();sync()}});video.addEventListener('play',sync);video.addEventListener('pause',sync);document.addEventListener('visibilitychange',()=>document.hidden?video.pause():play());reduced.addEventListener('change',()=>reduced.matches?video.pause():play());sync()}
export function bindMotifMotion(){if(matchMedia('(prefers-reduced-motion: reduce)').matches)return;const observer=new IntersectionObserver(entries=>{for(const entry of entries){if(!entry.isIntersecting)continue;entry.target.classList.add('is-visible');observer.unobserve(entry.target)}},{threshold:.5});document.querySelectorAll('.motif,.method-motif,.source-directory .brand-photo').forEach(el=>observer.observe(el))}
export function bindSpecialistReviews(){document.querySelectorAll('[data-specialist-reviews]').forEach(root=>{
 const track=root.querySelector('.specialist-review-stage'),stories=[...root.querySelectorAll('[data-review-story]')],position=root.querySelector('[data-review-position]'),reduced=matchMedia('(prefers-reduced-motion: reduce)'),prev=root.querySelector('[data-review-step="-1"]'),next=root.querySelector('[data-review-step="1"]');
 const update=()=>{
  const start=stories[0].offsetLeft,closest=stories.reduce((best,story,i)=>Math.abs(story.offsetLeft-start-track.scrollLeft)<Math.abs(stories[best].offsetLeft-start-track.scrollLeft)?i:best,0),visible=matchMedia('(max-width: 760px)').matches?1:2,end=Math.min(stories.length,closest+visible);
  position.textContent=String(closest+1).padStart(2,'0')+(visible>1?'–'+String(end).padStart(2,'0'):'');
  const height=Math.max(...stories.map(story=>{const css=getComputedStyle(story);return story.querySelector('.review-image-scroll').offsetHeight+parseFloat(css.paddingTop)+parseFloat(css.paddingBottom)}));
  track.style.height=Math.ceil(height)+10+'px';
  prev.disabled=track.scrollLeft<2;next.disabled=track.scrollLeft>=track.scrollWidth-track.clientWidth-2;
 };
 track.addEventListener('scroll',update,{passive:true});window.addEventListener('resize',update,{passive:true});
 const resize=new ResizeObserver(update);stories.forEach(story=>resize.observe(story.querySelector('.review-image-scroll')));
 root.querySelectorAll('img').forEach(image=>{image.loading='eager';image.addEventListener('load',update,{once:true})});requestAnimationFrame(update);
 root.querySelectorAll('[data-review-step]').forEach(button=>button.addEventListener('click',()=>track.scrollBy({left:Number(button.dataset.reviewStep)*(stories[0].getBoundingClientRect().width+16),behavior:reduced.matches?'instant':'smooth'})));
})}
export {originalHero,source as originalSource};
export function restoredServiceTail(){return ['rec624822675','rec624826019','rec624834535','rec624835656','rec625263103','rec625261042','rec627014195','rec625261741'].map(id=>block(rec('services',id))).join('')}
document.addEventListener('click',e=>{const a=e.target.closest('a[href^="#detail-"]');if(a){const d=document.getElementById(a.hash.slice(1));if(d)d.open=true}});
